// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use crate::{ModbusException, ModelSpec};
use core::cmp::min;

static POINTS: [PointDetails<()>; 93] = [
    PointDetails {
        point: |()| Point::ModelId,
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |()| Point::ModelLength,
        size: 1,
        start_address: 1,
    },
    PointDetails {
        point: |()| Point::CertUid,
        size: 1,
        start_address: 2,
    },
    PointDetails {
        point: |()| Point::CertRole,
        size: 1,
        start_address: 3,
    },
    PointDetails {
        point: |()| Point::Format,
        size: 1,
        start_address: 4,
    },
    PointDetails {
        point: |()| Point::Typ,
        size: 1,
        start_address: 5,
    },
    PointDetails {
        point: |()| Point::TotalLength,
        size: 1,
        start_address: 6,
    },
    PointDetails {
        point: |()| Point::FragmentLength,
        size: 1,
        start_address: 7,
    },
    PointDetails {
        point: |()| Point::Frag1,
        size: 1,
        start_address: 8,
    },
    PointDetails {
        point: |()| Point::Frg2,
        size: 1,
        start_address: 9,
    },
    PointDetails {
        point: |()| Point::Frg3,
        size: 1,
        start_address: 10,
    },
    PointDetails {
        point: |()| Point::Frg4,
        size: 1,
        start_address: 11,
    },
    PointDetails {
        point: |()| Point::Frg5,
        size: 1,
        start_address: 12,
    },
    PointDetails {
        point: |()| Point::Frg6,
        size: 1,
        start_address: 13,
    },
    PointDetails {
        point: |()| Point::Frg7,
        size: 1,
        start_address: 14,
    },
    PointDetails {
        point: |()| Point::Frg8,
        size: 1,
        start_address: 15,
    },
    PointDetails {
        point: |()| Point::Frg9,
        size: 1,
        start_address: 16,
    },
    PointDetails {
        point: |()| Point::Frg10,
        size: 1,
        start_address: 17,
    },
    PointDetails {
        point: |()| Point::Frg11,
        size: 1,
        start_address: 18,
    },
    PointDetails {
        point: |()| Point::Frg12,
        size: 1,
        start_address: 19,
    },
    PointDetails {
        point: |()| Point::Frg13,
        size: 1,
        start_address: 20,
    },
    PointDetails {
        point: |()| Point::Frg14,
        size: 1,
        start_address: 21,
    },
    PointDetails {
        point: |()| Point::Frg15,
        size: 1,
        start_address: 22,
    },
    PointDetails {
        point: |()| Point::Frg16,
        size: 1,
        start_address: 23,
    },
    PointDetails {
        point: |()| Point::Frg17,
        size: 1,
        start_address: 24,
    },
    PointDetails {
        point: |()| Point::Frg18,
        size: 1,
        start_address: 25,
    },
    PointDetails {
        point: |()| Point::Frg19,
        size: 1,
        start_address: 26,
    },
    PointDetails {
        point: |()| Point::Frg20,
        size: 1,
        start_address: 27,
    },
    PointDetails {
        point: |()| Point::Frg21,
        size: 1,
        start_address: 28,
    },
    PointDetails {
        point: |()| Point::Frg22,
        size: 1,
        start_address: 29,
    },
    PointDetails {
        point: |()| Point::Frg23,
        size: 1,
        start_address: 30,
    },
    PointDetails {
        point: |()| Point::Frg24,
        size: 1,
        start_address: 31,
    },
    PointDetails {
        point: |()| Point::Frg25,
        size: 1,
        start_address: 32,
    },
    PointDetails {
        point: |()| Point::Frg26,
        size: 1,
        start_address: 33,
    },
    PointDetails {
        point: |()| Point::Frg27,
        size: 1,
        start_address: 34,
    },
    PointDetails {
        point: |()| Point::Frg28,
        size: 1,
        start_address: 35,
    },
    PointDetails {
        point: |()| Point::Frg29,
        size: 1,
        start_address: 36,
    },
    PointDetails {
        point: |()| Point::Frg30,
        size: 1,
        start_address: 37,
    },
    PointDetails {
        point: |()| Point::Frg31,
        size: 1,
        start_address: 38,
    },
    PointDetails {
        point: |()| Point::Frg32,
        size: 1,
        start_address: 39,
    },
    PointDetails {
        point: |()| Point::Frg33,
        size: 1,
        start_address: 40,
    },
    PointDetails {
        point: |()| Point::Frg34,
        size: 1,
        start_address: 41,
    },
    PointDetails {
        point: |()| Point::Frg35,
        size: 1,
        start_address: 42,
    },
    PointDetails {
        point: |()| Point::Frg36,
        size: 1,
        start_address: 43,
    },
    PointDetails {
        point: |()| Point::Frg37,
        size: 1,
        start_address: 44,
    },
    PointDetails {
        point: |()| Point::Frg38,
        size: 1,
        start_address: 45,
    },
    PointDetails {
        point: |()| Point::Frg39,
        size: 1,
        start_address: 46,
    },
    PointDetails {
        point: |()| Point::Frg40,
        size: 1,
        start_address: 47,
    },
    PointDetails {
        point: |()| Point::Frg41,
        size: 1,
        start_address: 48,
    },
    PointDetails {
        point: |()| Point::Frg42,
        size: 1,
        start_address: 49,
    },
    PointDetails {
        point: |()| Point::Frg43,
        size: 1,
        start_address: 50,
    },
    PointDetails {
        point: |()| Point::Frg44,
        size: 1,
        start_address: 51,
    },
    PointDetails {
        point: |()| Point::Frg45,
        size: 1,
        start_address: 52,
    },
    PointDetails {
        point: |()| Point::Frg46,
        size: 1,
        start_address: 53,
    },
    PointDetails {
        point: |()| Point::Frg47,
        size: 1,
        start_address: 54,
    },
    PointDetails {
        point: |()| Point::Frg48,
        size: 1,
        start_address: 55,
    },
    PointDetails {
        point: |()| Point::Frg49,
        size: 1,
        start_address: 56,
    },
    PointDetails {
        point: |()| Point::Frg50,
        size: 1,
        start_address: 57,
    },
    PointDetails {
        point: |()| Point::Frg51,
        size: 1,
        start_address: 58,
    },
    PointDetails {
        point: |()| Point::Frg52,
        size: 1,
        start_address: 59,
    },
    PointDetails {
        point: |()| Point::Frg53,
        size: 1,
        start_address: 60,
    },
    PointDetails {
        point: |()| Point::Frg54,
        size: 1,
        start_address: 61,
    },
    PointDetails {
        point: |()| Point::Frg55,
        size: 1,
        start_address: 62,
    },
    PointDetails {
        point: |()| Point::Frg56,
        size: 1,
        start_address: 63,
    },
    PointDetails {
        point: |()| Point::Frg57,
        size: 1,
        start_address: 64,
    },
    PointDetails {
        point: |()| Point::Frg58,
        size: 1,
        start_address: 65,
    },
    PointDetails {
        point: |()| Point::Frg59,
        size: 1,
        start_address: 66,
    },
    PointDetails {
        point: |()| Point::Frg60,
        size: 1,
        start_address: 67,
    },
    PointDetails {
        point: |()| Point::Frg61,
        size: 1,
        start_address: 68,
    },
    PointDetails {
        point: |()| Point::Frg62,
        size: 1,
        start_address: 69,
    },
    PointDetails {
        point: |()| Point::Frg63,
        size: 1,
        start_address: 70,
    },
    PointDetails {
        point: |()| Point::Frg64,
        size: 1,
        start_address: 71,
    },
    PointDetails {
        point: |()| Point::Frg65,
        size: 1,
        start_address: 72,
    },
    PointDetails {
        point: |()| Point::Frg66,
        size: 1,
        start_address: 73,
    },
    PointDetails {
        point: |()| Point::Frg67,
        size: 1,
        start_address: 74,
    },
    PointDetails {
        point: |()| Point::Frg68,
        size: 1,
        start_address: 75,
    },
    PointDetails {
        point: |()| Point::Frg69,
        size: 1,
        start_address: 76,
    },
    PointDetails {
        point: |()| Point::Frg70,
        size: 1,
        start_address: 77,
    },
    PointDetails {
        point: |()| Point::Frg71,
        size: 1,
        start_address: 78,
    },
    PointDetails {
        point: |()| Point::Frg72,
        size: 1,
        start_address: 79,
    },
    PointDetails {
        point: |()| Point::Frg73,
        size: 1,
        start_address: 80,
    },
    PointDetails {
        point: |()| Point::Frg74,
        size: 1,
        start_address: 81,
    },
    PointDetails {
        point: |()| Point::Frg75,
        size: 1,
        start_address: 82,
    },
    PointDetails {
        point: |()| Point::Frg78,
        size: 1,
        start_address: 83,
    },
    PointDetails {
        point: |()| Point::Frg79,
        size: 1,
        start_address: 84,
    },
    PointDetails {
        point: |()| Point::Frag80,
        size: 1,
        start_address: 85,
    },
    PointDetails {
        point: |()| Point::Timestamp,
        size: 2,
        start_address: 86,
    },
    PointDetails {
        point: |()| Point::Milliseconds,
        size: 1,
        start_address: 88,
    },
    PointDetails {
        point: |()| Point::Sequence,
        size: 1,
        start_address: 89,
    },
    PointDetails {
        point: |()| Point::Uid,
        size: 1,
        start_address: 90,
    },
    PointDetails {
        point: |()| Point::Role,
        size: 1,
        start_address: 91,
    },
    PointDetails {
        point: |()| Point::Algorithm,
        size: 1,
        start_address: 92,
    },
    PointDetails {
        point: |()| Point::N,
        size: 1,
        start_address: 93,
    },
];

static REPEATING_POINTS: [PointDetails<()>; 1] = [PointDetails {
    point: |()| Point::RepeatingCert,
    size: 1,
    start_address: 0,
}];

#[derive(Debug)]
pub enum Point {
    ModelId,
    ModelLength,
    CertUid,
    CertRole,
    Format,
    Typ,
    TotalLength,
    FragmentLength,
    Frag1,
    Frg2,
    Frg3,
    Frg4,
    Frg5,
    Frg6,
    Frg7,
    Frg8,
    Frg9,
    Frg10,
    Frg11,
    Frg12,
    Frg13,
    Frg14,
    Frg15,
    Frg16,
    Frg17,
    Frg18,
    Frg19,
    Frg20,
    Frg21,
    Frg22,
    Frg23,
    Frg24,
    Frg25,
    Frg26,
    Frg27,
    Frg28,
    Frg29,
    Frg30,
    Frg31,
    Frg32,
    Frg33,
    Frg34,
    Frg35,
    Frg36,
    Frg37,
    Frg38,
    Frg39,
    Frg40,
    Frg41,
    Frg42,
    Frg43,
    Frg44,
    Frg45,
    Frg46,
    Frg47,
    Frg48,
    Frg49,
    Frg50,
    Frg51,
    Frg52,
    Frg53,
    Frg54,
    Frg55,
    Frg56,
    Frg57,
    Frg58,
    Frg59,
    Frg60,
    Frg61,
    Frg62,
    Frg63,
    Frg64,
    Frg65,
    Frg66,
    Frg67,
    Frg68,
    Frg69,
    Frg70,
    Frg71,
    Frg72,
    Frg73,
    Frg74,
    Frg75,
    Frg78,
    Frg79,
    Frag80,
    Timestamp,
    Milliseconds,
    Sequence,
    Uid,
    Role,
    Algorithm,
    N,
    RepeatingCert,
}

struct PointDetails<GroupIndexArgs> {
    point: fn(GroupIndexArgs) -> Point,
    start_address: u16,
    size: u16,
}

/// Marker for SunSpec model 9. Add it to a [`Sunspec`](crate::Sunspec) model list.
pub struct Model9;

impl<'ad> ModelSpec<'ad> for Model9 {
    const MODEL_ID: u16 = 9;
    type ReadAdapter = dyn ReadAdapter + 'ad;
    type WriteAdapter = dyn WriteAdapter + 'ad;

    fn model_length(&self) -> u16 {
        95
    }

    fn traverse_points_read<'a>(
        &self,
        adapter: Option<&Self::ReadAdapter>,
        buffer: &mut WritableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .chain(
                REPEATING_POINTS
                    .iter()
                    .map(move |p| (94 + p.start_address, p.size, (p.point)(()))),
            )
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            write_point_to_buffer(
                self,
                adapter,
                &point,
                &mut buffer.slice(cursor, word_count),
                point_offset,
            );
            cursor += word_count;
        }

        Ok(())
    }

    fn traverse_points_write<'a>(
        &self,
        adapter: &mut Self::WriteAdapter,
        buffer: &ReadableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .chain(
                REPEATING_POINTS
                    .iter()
                    .map(move |p| (94 + p.start_address, p.size, (p.point)(()))),
            )
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            if point_offset > 0 {
                return Err(ModbusException::IllegalDataAddress);
            }
            read_point_from_buffer(self, adapter, &point, &buffer.slice(cursor, word_count))?;
            cursor += word_count;
        }

        Ok(())
    }
}

pub(crate) fn write_point_to_buffer<'a>(
    model: &Model9,
    adapter: Option<&dyn ReadAdapter>,
    point: &Point,
    buffer: &mut WritableRegisterBuffer<'a>,
    offset: u16,
) {
    match point {
        Point::ModelId => {
            buffer.write_u16(9);
        }
        Point::ModelLength => {
            buffer.write_u16(model.model_length() - 2);
        }
        Point::CertUid => {
            if let Some(value) = adapter.map(|adapter| adapter.cert_uid()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::CertRole => {
            if let Some(value) = adapter.map(|adapter| adapter.cert_role()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Format => {
            if let Some(value) = adapter.map(|adapter| adapter.format()) {
                buffer.write_u16(value as u16);
            } else {
                buffer.write_u16(crate::not_implemented::ENUM16);
            }
        }
        Point::Typ => {
            if let Some(value) = adapter.map(|adapter| adapter.typ()) {
                buffer.write_u16(value as u16);
            } else {
                buffer.write_u16(crate::not_implemented::ENUM16);
            }
        }
        Point::TotalLength => {
            if let Some(value) = adapter.map(|adapter| adapter.total_length()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::FragmentLength => {
            if let Some(value) = adapter.map(|adapter| adapter.fragment_length()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frag1 => {
            if let Some(value) = adapter.map(|adapter| adapter.frag1()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg2 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg2()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg3 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg3()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg4 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg4()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg5 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg5()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg6 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg6()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg7 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg7()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg8 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg8()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg9 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg9()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg10 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg10()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg11 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg11()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg12 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg12()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg13 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg13()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg14 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg14()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg15 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg15()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg16 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg16()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg17 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg17()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg18 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg18()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg19 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg19()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg20 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg20()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg21 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg21()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg22 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg22()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg23 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg23()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg24 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg24()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg25 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg25()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg26 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg26()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg27 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg27()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg28 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg28()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg29 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg29()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg30 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg30()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg31 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg31()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg32 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg32()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg33 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg33()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg34 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg34()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg35 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg35()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg36 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg36()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg37 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg37()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg38 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg38()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg39 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg39()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg40 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg40()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg41 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg41()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg42 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg42()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg43 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg43()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg44 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg44()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg45 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg45()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg46 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg46()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg47 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg47()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg48 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg48()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg49 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg49()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg50 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg50()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg51 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg51()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg52 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg52()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg53 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg53()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg54 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg54()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg55 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg55()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg56 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg56()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg57 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg57()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg58 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg58()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg59 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg59()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg60 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg60()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg61 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg61()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg62 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg62()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg63 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg63()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg64 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg64()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg65 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg65()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg66 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg66()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg67 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg67()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg68 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg68()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg69 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg69()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg70 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg70()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg71 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg71()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg72 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg72()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg73 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg73()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg74 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg74()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg75 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg75()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg78 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg78()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frg79 => {
            if let Some(value) = adapter.map(|adapter| adapter.frg79()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Frag80 => {
            if let Some(value) = adapter.map(|adapter| adapter.frag80()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Timestamp => {
            if let Some(value) = adapter.map(|adapter| adapter.timestamp()) {
                buffer.write_u32(value, offset);
            } else {
                buffer.write_u32(crate::not_implemented::UINT32, offset);
            }
        }
        Point::Milliseconds => {
            if let Some(value) = adapter.map(|adapter| adapter.milliseconds()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Sequence => {
            if let Some(value) = adapter.map(|adapter| adapter.sequence()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Uid => {
            if let Some(value) = adapter.map(|adapter| adapter.uid()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Role => {
            if let Some(value) = adapter.map(|adapter| adapter.role()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Algorithm => {
            if let Some(value) = adapter.map(|adapter| adapter.algorithm()) {
                buffer.write_u16(value as u16);
            } else {
                buffer.write_u16(crate::not_implemented::ENUM16);
            }
        }
        Point::N => {
            if let Some(value) = adapter.map(|adapter| adapter.n()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::RepeatingCert => {
            if let Some(value) = adapter.map(|adapter| adapter.repeating_cert()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
    }
}

pub(crate) fn read_point_from_buffer<'a>(
    model: &Model9,
    adapter: &mut dyn WriteAdapter,
    point: &Point,
    buffer: &ReadableRegisterBuffer<'a>,
) -> Result<(), ModbusException> {
    match point {
        Point::CertUid => {
            let value = buffer.read_u16()?;
            adapter.set_cert_uid(value);
            Ok(())
        }
        Point::CertRole => {
            let value = buffer.read_u16()?;
            adapter.set_cert_role(value);
            Ok(())
        }
        Point::Format => {
            let value = buffer.read_u16()?;
            let enum_value = Fmt::from_repr(value).ok_or(ModbusException::IllegalDataValue)?;
            adapter.set_format(enum_value);
            Ok(())
        }
        Point::Typ => {
            let value = buffer.read_u16()?;
            let enum_value = Typ::from_repr(value).ok_or(ModbusException::IllegalDataValue)?;
            adapter.set_typ(enum_value);
            Ok(())
        }
        Point::TotalLength => {
            let value = buffer.read_u16()?;
            adapter.set_total_length(value);
            Ok(())
        }
        Point::FragmentLength => {
            let value = buffer.read_u16()?;
            adapter.set_fragment_length(value);
            Ok(())
        }
        Point::Frag1 => {
            let value = buffer.read_u16()?;
            adapter.set_frag1(value);
            Ok(())
        }
        Point::Frg2 => {
            let value = buffer.read_u16()?;
            adapter.set_frg2(value);
            Ok(())
        }
        Point::Frg3 => {
            let value = buffer.read_u16()?;
            adapter.set_frg3(value);
            Ok(())
        }
        Point::Frg4 => {
            let value = buffer.read_u16()?;
            adapter.set_frg4(value);
            Ok(())
        }
        Point::Frg5 => {
            let value = buffer.read_u16()?;
            adapter.set_frg5(value);
            Ok(())
        }
        Point::Frg6 => {
            let value = buffer.read_u16()?;
            adapter.set_frg6(value);
            Ok(())
        }
        Point::Frg7 => {
            let value = buffer.read_u16()?;
            adapter.set_frg7(value);
            Ok(())
        }
        Point::Frg8 => {
            let value = buffer.read_u16()?;
            adapter.set_frg8(value);
            Ok(())
        }
        Point::Frg9 => {
            let value = buffer.read_u16()?;
            adapter.set_frg9(value);
            Ok(())
        }
        Point::Frg10 => {
            let value = buffer.read_u16()?;
            adapter.set_frg10(value);
            Ok(())
        }
        Point::Frg11 => {
            let value = buffer.read_u16()?;
            adapter.set_frg11(value);
            Ok(())
        }
        Point::Frg12 => {
            let value = buffer.read_u16()?;
            adapter.set_frg12(value);
            Ok(())
        }
        Point::Frg13 => {
            let value = buffer.read_u16()?;
            adapter.set_frg13(value);
            Ok(())
        }
        Point::Frg14 => {
            let value = buffer.read_u16()?;
            adapter.set_frg14(value);
            Ok(())
        }
        Point::Frg15 => {
            let value = buffer.read_u16()?;
            adapter.set_frg15(value);
            Ok(())
        }
        Point::Frg16 => {
            let value = buffer.read_u16()?;
            adapter.set_frg16(value);
            Ok(())
        }
        Point::Frg17 => {
            let value = buffer.read_u16()?;
            adapter.set_frg17(value);
            Ok(())
        }
        Point::Frg18 => {
            let value = buffer.read_u16()?;
            adapter.set_frg18(value);
            Ok(())
        }
        Point::Frg19 => {
            let value = buffer.read_u16()?;
            adapter.set_frg19(value);
            Ok(())
        }
        Point::Frg20 => {
            let value = buffer.read_u16()?;
            adapter.set_frg20(value);
            Ok(())
        }
        Point::Frg21 => {
            let value = buffer.read_u16()?;
            adapter.set_frg21(value);
            Ok(())
        }
        Point::Frg22 => {
            let value = buffer.read_u16()?;
            adapter.set_frg22(value);
            Ok(())
        }
        Point::Frg23 => {
            let value = buffer.read_u16()?;
            adapter.set_frg23(value);
            Ok(())
        }
        Point::Frg24 => {
            let value = buffer.read_u16()?;
            adapter.set_frg24(value);
            Ok(())
        }
        Point::Frg25 => {
            let value = buffer.read_u16()?;
            adapter.set_frg25(value);
            Ok(())
        }
        Point::Frg26 => {
            let value = buffer.read_u16()?;
            adapter.set_frg26(value);
            Ok(())
        }
        Point::Frg27 => {
            let value = buffer.read_u16()?;
            adapter.set_frg27(value);
            Ok(())
        }
        Point::Frg28 => {
            let value = buffer.read_u16()?;
            adapter.set_frg28(value);
            Ok(())
        }
        Point::Frg29 => {
            let value = buffer.read_u16()?;
            adapter.set_frg29(value);
            Ok(())
        }
        Point::Frg30 => {
            let value = buffer.read_u16()?;
            adapter.set_frg30(value);
            Ok(())
        }
        Point::Frg31 => {
            let value = buffer.read_u16()?;
            adapter.set_frg31(value);
            Ok(())
        }
        Point::Frg32 => {
            let value = buffer.read_u16()?;
            adapter.set_frg32(value);
            Ok(())
        }
        Point::Frg33 => {
            let value = buffer.read_u16()?;
            adapter.set_frg33(value);
            Ok(())
        }
        Point::Frg34 => {
            let value = buffer.read_u16()?;
            adapter.set_frg34(value);
            Ok(())
        }
        Point::Frg35 => {
            let value = buffer.read_u16()?;
            adapter.set_frg35(value);
            Ok(())
        }
        Point::Frg36 => {
            let value = buffer.read_u16()?;
            adapter.set_frg36(value);
            Ok(())
        }
        Point::Frg37 => {
            let value = buffer.read_u16()?;
            adapter.set_frg37(value);
            Ok(())
        }
        Point::Frg38 => {
            let value = buffer.read_u16()?;
            adapter.set_frg38(value);
            Ok(())
        }
        Point::Frg39 => {
            let value = buffer.read_u16()?;
            adapter.set_frg39(value);
            Ok(())
        }
        Point::Frg40 => {
            let value = buffer.read_u16()?;
            adapter.set_frg40(value);
            Ok(())
        }
        Point::Frg41 => {
            let value = buffer.read_u16()?;
            adapter.set_frg41(value);
            Ok(())
        }
        Point::Frg42 => {
            let value = buffer.read_u16()?;
            adapter.set_frg42(value);
            Ok(())
        }
        Point::Frg43 => {
            let value = buffer.read_u16()?;
            adapter.set_frg43(value);
            Ok(())
        }
        Point::Frg44 => {
            let value = buffer.read_u16()?;
            adapter.set_frg44(value);
            Ok(())
        }
        Point::Frg45 => {
            let value = buffer.read_u16()?;
            adapter.set_frg45(value);
            Ok(())
        }
        Point::Frg46 => {
            let value = buffer.read_u16()?;
            adapter.set_frg46(value);
            Ok(())
        }
        Point::Frg47 => {
            let value = buffer.read_u16()?;
            adapter.set_frg47(value);
            Ok(())
        }
        Point::Frg48 => {
            let value = buffer.read_u16()?;
            adapter.set_frg48(value);
            Ok(())
        }
        Point::Frg49 => {
            let value = buffer.read_u16()?;
            adapter.set_frg49(value);
            Ok(())
        }
        Point::Frg50 => {
            let value = buffer.read_u16()?;
            adapter.set_frg50(value);
            Ok(())
        }
        Point::Frg51 => {
            let value = buffer.read_u16()?;
            adapter.set_frg51(value);
            Ok(())
        }
        Point::Frg52 => {
            let value = buffer.read_u16()?;
            adapter.set_frg52(value);
            Ok(())
        }
        Point::Frg53 => {
            let value = buffer.read_u16()?;
            adapter.set_frg53(value);
            Ok(())
        }
        Point::Frg54 => {
            let value = buffer.read_u16()?;
            adapter.set_frg54(value);
            Ok(())
        }
        Point::Frg55 => {
            let value = buffer.read_u16()?;
            adapter.set_frg55(value);
            Ok(())
        }
        Point::Frg56 => {
            let value = buffer.read_u16()?;
            adapter.set_frg56(value);
            Ok(())
        }
        Point::Frg57 => {
            let value = buffer.read_u16()?;
            adapter.set_frg57(value);
            Ok(())
        }
        Point::Frg58 => {
            let value = buffer.read_u16()?;
            adapter.set_frg58(value);
            Ok(())
        }
        Point::Frg59 => {
            let value = buffer.read_u16()?;
            adapter.set_frg59(value);
            Ok(())
        }
        Point::Frg60 => {
            let value = buffer.read_u16()?;
            adapter.set_frg60(value);
            Ok(())
        }
        Point::Frg61 => {
            let value = buffer.read_u16()?;
            adapter.set_frg61(value);
            Ok(())
        }
        Point::Frg62 => {
            let value = buffer.read_u16()?;
            adapter.set_frg62(value);
            Ok(())
        }
        Point::Frg63 => {
            let value = buffer.read_u16()?;
            adapter.set_frg63(value);
            Ok(())
        }
        Point::Frg64 => {
            let value = buffer.read_u16()?;
            adapter.set_frg64(value);
            Ok(())
        }
        Point::Frg65 => {
            let value = buffer.read_u16()?;
            adapter.set_frg65(value);
            Ok(())
        }
        Point::Frg66 => {
            let value = buffer.read_u16()?;
            adapter.set_frg66(value);
            Ok(())
        }
        Point::Frg67 => {
            let value = buffer.read_u16()?;
            adapter.set_frg67(value);
            Ok(())
        }
        Point::Frg68 => {
            let value = buffer.read_u16()?;
            adapter.set_frg68(value);
            Ok(())
        }
        Point::Frg69 => {
            let value = buffer.read_u16()?;
            adapter.set_frg69(value);
            Ok(())
        }
        Point::Frg70 => {
            let value = buffer.read_u16()?;
            adapter.set_frg70(value);
            Ok(())
        }
        Point::Frg71 => {
            let value = buffer.read_u16()?;
            adapter.set_frg71(value);
            Ok(())
        }
        Point::Frg72 => {
            let value = buffer.read_u16()?;
            adapter.set_frg72(value);
            Ok(())
        }
        Point::Frg73 => {
            let value = buffer.read_u16()?;
            adapter.set_frg73(value);
            Ok(())
        }
        Point::Frg74 => {
            let value = buffer.read_u16()?;
            adapter.set_frg74(value);
            Ok(())
        }
        Point::Frg75 => {
            let value = buffer.read_u16()?;
            adapter.set_frg75(value);
            Ok(())
        }
        Point::Frg78 => {
            let value = buffer.read_u16()?;
            adapter.set_frg78(value);
            Ok(())
        }
        Point::Frg79 => {
            let value = buffer.read_u16()?;
            adapter.set_frg79(value);
            Ok(())
        }
        Point::Frag80 => {
            let value = buffer.read_u16()?;
            adapter.set_frag80(value);
            Ok(())
        }
        Point::Timestamp => {
            let value = buffer.read_u32()?;
            adapter.set_timestamp(value);
            Ok(())
        }
        Point::Milliseconds => {
            let value = buffer.read_u16()?;
            adapter.set_milliseconds(value);
            Ok(())
        }
        Point::Sequence => {
            let value = buffer.read_u16()?;
            adapter.set_sequence(value);
            Ok(())
        }
        Point::Uid => {
            let value = buffer.read_u16()?;
            adapter.set_uid(value);
            Ok(())
        }
        Point::Role => {
            let value = buffer.read_u16()?;
            adapter.set_role(value);
            Ok(())
        }
        Point::Algorithm => {
            let value = buffer.read_u16()?;
            let enum_value = Alg::from_repr(value).ok_or(ModbusException::IllegalDataValue)?;
            adapter.set_algorithm(enum_value);
            Ok(())
        }
        Point::N => {
            let value = buffer.read_u16()?;
            adapter.set_n(value);
            Ok(())
        }
        Point::RepeatingCert => {
            let value = buffer.read_u16()?;
            adapter.set_repeating_cert(value);
            Ok(())
        }
        _ => Err(ModbusException::IllegalDataAddress),
    }
}

pub trait ReadAdapter {
    /// Cert_UID (CertUID)
    ///
    /// User ID for this certificate
    fn cert_uid(&self) -> u16;

    /// Cert_Role (CertRole)
    ///
    /// Role for this certificate
    fn cert_role(&self) -> u16;

    /// Format (Fmt)
    ///
    /// Format of this certificate
    fn format(&self) -> Fmt;

    /// Type (Typ)
    ///
    /// Type of this certificate
    fn typ(&self) -> Typ;

    /// Total Length (TotLn)
    ///
    /// Total Length of the Certificate
    ///
    /// In registers, zero padded.
    fn total_length(&self) -> u16;

    /// Fragment length (FrgLn)
    ///
    /// Length of this fragment
    ///
    /// Maximum fragment length is 80 registers
    fn fragment_length(&self) -> u16;

    /// Frag1 (Frg1)
    ///
    /// First word of this fragment
    fn frag1(&self) -> u16;

    /// Frg2
    fn frg2(&self) -> u16;

    /// Frg3
    fn frg3(&self) -> u16;

    /// Frg4
    fn frg4(&self) -> u16;

    /// Frg5
    fn frg5(&self) -> u16;

    /// Frg6
    fn frg6(&self) -> u16;

    /// Frg7
    fn frg7(&self) -> u16;

    /// Frg8
    fn frg8(&self) -> u16;

    /// Frg9
    fn frg9(&self) -> u16;

    /// Frg10
    fn frg10(&self) -> u16;

    /// Frg11
    fn frg11(&self) -> u16;

    /// Frg12
    fn frg12(&self) -> u16;

    /// Frg13
    fn frg13(&self) -> u16;

    /// Frg14
    fn frg14(&self) -> u16;

    /// Frg15
    fn frg15(&self) -> u16;

    /// Frg16
    fn frg16(&self) -> u16;

    /// Frg17
    fn frg17(&self) -> u16;

    /// Frg18
    fn frg18(&self) -> u16;

    /// Frg19
    fn frg19(&self) -> u16;

    /// Frg20
    fn frg20(&self) -> u16;

    /// Frg21
    fn frg21(&self) -> u16;

    /// Frg22
    fn frg22(&self) -> u16;

    /// Frg23
    fn frg23(&self) -> u16;

    /// Frg24
    fn frg24(&self) -> u16;

    /// Frg25
    fn frg25(&self) -> u16;

    /// Frg26
    fn frg26(&self) -> u16;

    /// Frg27
    fn frg27(&self) -> u16;

    /// Frg28
    fn frg28(&self) -> u16;

    /// Frg29
    fn frg29(&self) -> u16;

    /// Frg30
    fn frg30(&self) -> u16;

    /// Frg31
    fn frg31(&self) -> u16;

    /// Frg32
    fn frg32(&self) -> u16;

    /// Frg33
    fn frg33(&self) -> u16;

    /// Frg34
    fn frg34(&self) -> u16;

    /// Frg35
    fn frg35(&self) -> u16;

    /// Frg36
    fn frg36(&self) -> u16;

    /// Frg37
    fn frg37(&self) -> u16;

    /// Frg38
    fn frg38(&self) -> u16;

    /// Frg39
    fn frg39(&self) -> u16;

    /// Frg40
    fn frg40(&self) -> u16;

    /// Frg41
    fn frg41(&self) -> u16;

    /// Frg42
    fn frg42(&self) -> u16;

    /// Frg43
    fn frg43(&self) -> u16;

    /// Frg44
    fn frg44(&self) -> u16;

    /// Frg45
    fn frg45(&self) -> u16;

    /// Frg46
    fn frg46(&self) -> u16;

    /// Frg47
    fn frg47(&self) -> u16;

    /// Frg48
    fn frg48(&self) -> u16;

    /// Frg49
    fn frg49(&self) -> u16;

    /// Frg50
    fn frg50(&self) -> u16;

    /// Frg51
    fn frg51(&self) -> u16;

    /// Frg52
    fn frg52(&self) -> u16;

    /// Frg53
    fn frg53(&self) -> u16;

    /// Frg54
    fn frg54(&self) -> u16;

    /// Frg55
    fn frg55(&self) -> u16;

    /// Frg56
    fn frg56(&self) -> u16;

    /// Frg57
    fn frg57(&self) -> u16;

    /// Frg58
    fn frg58(&self) -> u16;

    /// Frg59
    fn frg59(&self) -> u16;

    /// Frg60
    fn frg60(&self) -> u16;

    /// Frg61
    fn frg61(&self) -> u16;

    /// Frg62
    fn frg62(&self) -> u16;

    /// Frg63
    fn frg63(&self) -> u16;

    /// Frg64
    fn frg64(&self) -> u16;

    /// Frg65
    fn frg65(&self) -> u16;

    /// Frg66
    fn frg66(&self) -> u16;

    /// Frg67
    fn frg67(&self) -> u16;

    /// Frg68
    fn frg68(&self) -> u16;

    /// Frg69
    fn frg69(&self) -> u16;

    /// Frg70
    fn frg70(&self) -> u16;

    /// Frg71
    fn frg71(&self) -> u16;

    /// Frg72
    fn frg72(&self) -> u16;

    /// Frg73
    fn frg73(&self) -> u16;

    /// Frg74
    fn frg74(&self) -> u16;

    /// Frg75
    fn frg75(&self) -> u16;

    /// Frg78
    fn frg78(&self) -> u16;

    /// Frg79
    fn frg79(&self) -> u16;

    /// Frag80 (Frg80)
    ///
    /// Last word of this fragment
    fn frag80(&self) -> u16;

    /// Timestamp (Ts)
    ///
    /// Timestamp value is the number of seconds since January 1, 2000
    fn timestamp(&self) -> u32;

    /// Milliseconds (Ms)
    ///
    /// Millisecond counter 0-999
    fn milliseconds(&self) -> u16;

    /// Sequence (Seq)
    ///
    /// Sequence number of request
    ///
    /// Shall be advanced for each request
    fn sequence(&self) -> u16;

    /// UID (UID)
    ///
    /// User ID for the request signature
    fn uid(&self) -> u16;

    /// Role (Role)
    ///
    /// Signing key used 0-5
    ///
    /// Each controller is assigned a key index that maps to their access control role
    fn role(&self) -> u16;

    /// Algorithm (Alg)
    ///
    /// Algorithm used to compute the digital signature
    ///
    /// For future proof
    fn algorithm(&self) -> Alg;

    /// N (N)
    ///
    /// Number of registers to follow for the certificate
    fn n(&self) -> u16;

    /// Cert
    fn repeating_cert(&self) -> u16;
}

pub trait WriteAdapter {
    /// Cert_UID (CertUID)
    ///
    /// User ID for this certificate
    fn set_cert_uid(&mut self, value: u16);

    /// Cert_Role (CertRole)
    ///
    /// Role for this certificate
    fn set_cert_role(&mut self, value: u16);

    /// Format (Fmt)
    ///
    /// Format of this certificate
    fn set_format(&mut self, value: Fmt);

    /// Type (Typ)
    ///
    /// Type of this certificate
    fn set_typ(&mut self, value: Typ);

    /// Total Length (TotLn)
    ///
    /// Total Length of the Certificate
    ///
    /// In registers, zero padded.
    fn set_total_length(&mut self, value: u16);

    /// Fragment length (FrgLn)
    ///
    /// Length of this fragment
    ///
    /// Maximum fragment length is 80 registers
    fn set_fragment_length(&mut self, value: u16);

    /// Frag1 (Frg1)
    ///
    /// First word of this fragment
    fn set_frag1(&mut self, value: u16);

    /// Frg2
    fn set_frg2(&mut self, value: u16);

    /// Frg3
    fn set_frg3(&mut self, value: u16);

    /// Frg4
    fn set_frg4(&mut self, value: u16);

    /// Frg5
    fn set_frg5(&mut self, value: u16);

    /// Frg6
    fn set_frg6(&mut self, value: u16);

    /// Frg7
    fn set_frg7(&mut self, value: u16);

    /// Frg8
    fn set_frg8(&mut self, value: u16);

    /// Frg9
    fn set_frg9(&mut self, value: u16);

    /// Frg10
    fn set_frg10(&mut self, value: u16);

    /// Frg11
    fn set_frg11(&mut self, value: u16);

    /// Frg12
    fn set_frg12(&mut self, value: u16);

    /// Frg13
    fn set_frg13(&mut self, value: u16);

    /// Frg14
    fn set_frg14(&mut self, value: u16);

    /// Frg15
    fn set_frg15(&mut self, value: u16);

    /// Frg16
    fn set_frg16(&mut self, value: u16);

    /// Frg17
    fn set_frg17(&mut self, value: u16);

    /// Frg18
    fn set_frg18(&mut self, value: u16);

    /// Frg19
    fn set_frg19(&mut self, value: u16);

    /// Frg20
    fn set_frg20(&mut self, value: u16);

    /// Frg21
    fn set_frg21(&mut self, value: u16);

    /// Frg22
    fn set_frg22(&mut self, value: u16);

    /// Frg23
    fn set_frg23(&mut self, value: u16);

    /// Frg24
    fn set_frg24(&mut self, value: u16);

    /// Frg25
    fn set_frg25(&mut self, value: u16);

    /// Frg26
    fn set_frg26(&mut self, value: u16);

    /// Frg27
    fn set_frg27(&mut self, value: u16);

    /// Frg28
    fn set_frg28(&mut self, value: u16);

    /// Frg29
    fn set_frg29(&mut self, value: u16);

    /// Frg30
    fn set_frg30(&mut self, value: u16);

    /// Frg31
    fn set_frg31(&mut self, value: u16);

    /// Frg32
    fn set_frg32(&mut self, value: u16);

    /// Frg33
    fn set_frg33(&mut self, value: u16);

    /// Frg34
    fn set_frg34(&mut self, value: u16);

    /// Frg35
    fn set_frg35(&mut self, value: u16);

    /// Frg36
    fn set_frg36(&mut self, value: u16);

    /// Frg37
    fn set_frg37(&mut self, value: u16);

    /// Frg38
    fn set_frg38(&mut self, value: u16);

    /// Frg39
    fn set_frg39(&mut self, value: u16);

    /// Frg40
    fn set_frg40(&mut self, value: u16);

    /// Frg41
    fn set_frg41(&mut self, value: u16);

    /// Frg42
    fn set_frg42(&mut self, value: u16);

    /// Frg43
    fn set_frg43(&mut self, value: u16);

    /// Frg44
    fn set_frg44(&mut self, value: u16);

    /// Frg45
    fn set_frg45(&mut self, value: u16);

    /// Frg46
    fn set_frg46(&mut self, value: u16);

    /// Frg47
    fn set_frg47(&mut self, value: u16);

    /// Frg48
    fn set_frg48(&mut self, value: u16);

    /// Frg49
    fn set_frg49(&mut self, value: u16);

    /// Frg50
    fn set_frg50(&mut self, value: u16);

    /// Frg51
    fn set_frg51(&mut self, value: u16);

    /// Frg52
    fn set_frg52(&mut self, value: u16);

    /// Frg53
    fn set_frg53(&mut self, value: u16);

    /// Frg54
    fn set_frg54(&mut self, value: u16);

    /// Frg55
    fn set_frg55(&mut self, value: u16);

    /// Frg56
    fn set_frg56(&mut self, value: u16);

    /// Frg57
    fn set_frg57(&mut self, value: u16);

    /// Frg58
    fn set_frg58(&mut self, value: u16);

    /// Frg59
    fn set_frg59(&mut self, value: u16);

    /// Frg60
    fn set_frg60(&mut self, value: u16);

    /// Frg61
    fn set_frg61(&mut self, value: u16);

    /// Frg62
    fn set_frg62(&mut self, value: u16);

    /// Frg63
    fn set_frg63(&mut self, value: u16);

    /// Frg64
    fn set_frg64(&mut self, value: u16);

    /// Frg65
    fn set_frg65(&mut self, value: u16);

    /// Frg66
    fn set_frg66(&mut self, value: u16);

    /// Frg67
    fn set_frg67(&mut self, value: u16);

    /// Frg68
    fn set_frg68(&mut self, value: u16);

    /// Frg69
    fn set_frg69(&mut self, value: u16);

    /// Frg70
    fn set_frg70(&mut self, value: u16);

    /// Frg71
    fn set_frg71(&mut self, value: u16);

    /// Frg72
    fn set_frg72(&mut self, value: u16);

    /// Frg73
    fn set_frg73(&mut self, value: u16);

    /// Frg74
    fn set_frg74(&mut self, value: u16);

    /// Frg75
    fn set_frg75(&mut self, value: u16);

    /// Frg78
    fn set_frg78(&mut self, value: u16);

    /// Frg79
    fn set_frg79(&mut self, value: u16);

    /// Frag80 (Frg80)
    ///
    /// Last word of this fragment
    fn set_frag80(&mut self, value: u16);

    /// Timestamp (Ts)
    ///
    /// Timestamp value is the number of seconds since January 1, 2000
    fn set_timestamp(&mut self, value: u32);

    /// Milliseconds (Ms)
    ///
    /// Millisecond counter 0-999
    fn set_milliseconds(&mut self, value: u16);

    /// Sequence (Seq)
    ///
    /// Sequence number of request
    ///
    /// Shall be advanced for each request
    fn set_sequence(&mut self, value: u16);

    /// UID (UID)
    ///
    /// User ID for the request signature
    fn set_uid(&mut self, value: u16);

    /// Role (Role)
    ///
    /// Signing key used 0-5
    ///
    /// Each controller is assigned a key index that maps to their access control role
    fn set_role(&mut self, value: u16);

    /// Algorithm (Alg)
    ///
    /// Algorithm used to compute the digital signature
    ///
    /// For future proof
    fn set_algorithm(&mut self, value: Alg);

    /// N (N)
    ///
    /// Number of registers to follow for the certificate
    fn set_n(&mut self, value: u16);

    /// Cert
    fn set_repeating_cert(&mut self, value: u16);
}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model9Alg {
    /// For test purposes only
    None = 0,
    AesGmac64 = 1,
    Ecc256 = 2,
}

impl Model9Alg {
    pub fn from_repr(repr: u16) -> Option<Model9Alg> {
        match repr {
            0 => Some(Model9Alg::None),
            1 => Some(Model9Alg::AesGmac64),
            2 => Some(Model9Alg::Ecc256),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model9Alg`] - only `Model9Alg` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `Alg` distinct from another model's point of the same name.
pub type Alg = Model9Alg;

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model9Fmt {
    None = 0,
    X509Pem = 1,
    X509Der = 2,
}

impl Model9Fmt {
    pub fn from_repr(repr: u16) -> Option<Model9Fmt> {
        match repr {
            0 => Some(Model9Fmt::None),
            1 => Some(Model9Fmt::X509Pem),
            2 => Some(Model9Fmt::X509Der),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model9Fmt`] - only `Model9Fmt` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `Fmt` distinct from another model's point of the same name.
pub type Fmt = Model9Fmt;

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model9Typ {
    DevKeyPair = 0,
    DevSharedKey = 1,
    OperatorPub = 2,
    OperatorShared = 3,
    CaPub = 4,
}

impl Model9Typ {
    pub fn from_repr(repr: u16) -> Option<Model9Typ> {
        match repr {
            0 => Some(Model9Typ::DevKeyPair),
            1 => Some(Model9Typ::DevSharedKey),
            2 => Some(Model9Typ::OperatorPub),
            3 => Some(Model9Typ::OperatorShared),
            4 => Some(Model9Typ::CaPub),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model9Typ`] - only `Model9Typ` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `Typ` distinct from another model's point of the same name.
pub type Typ = Model9Typ;
