// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use crate::{ModbusException, ModelSpec};
use core::cmp::min;

static POINTS: [PointDetails<()>; 89] = [
    PointDetails {
        point: |()| Point::ModelId,
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |()| Point::ModelLength,
        size: 1,
        start_address: 1,
    },
    PointDetails {
        point: |()| Point::X,
        size: 1,
        start_address: 2,
    },
    PointDetails {
        point: |()| Point::Offset1,
        size: 1,
        start_address: 3,
    },
    PointDetails {
        point: |()| Point::Value1,
        size: 1,
        start_address: 4,
    },
    PointDetails {
        point: |()| Point::Off2,
        size: 1,
        start_address: 5,
    },
    PointDetails {
        point: |()| Point::Val2,
        size: 1,
        start_address: 6,
    },
    PointDetails {
        point: |()| Point::Off3,
        size: 1,
        start_address: 7,
    },
    PointDetails {
        point: |()| Point::Val3,
        size: 1,
        start_address: 8,
    },
    PointDetails {
        point: |()| Point::Off4,
        size: 1,
        start_address: 9,
    },
    PointDetails {
        point: |()| Point::Val4,
        size: 1,
        start_address: 10,
    },
    PointDetails {
        point: |()| Point::Off5,
        size: 1,
        start_address: 11,
    },
    PointDetails {
        point: |()| Point::Val5,
        size: 1,
        start_address: 12,
    },
    PointDetails {
        point: |()| Point::Off6,
        size: 1,
        start_address: 13,
    },
    PointDetails {
        point: |()| Point::Val6,
        size: 1,
        start_address: 14,
    },
    PointDetails {
        point: |()| Point::Off7,
        size: 1,
        start_address: 15,
    },
    PointDetails {
        point: |()| Point::Val7,
        size: 1,
        start_address: 16,
    },
    PointDetails {
        point: |()| Point::Off8,
        size: 1,
        start_address: 17,
    },
    PointDetails {
        point: |()| Point::Val8,
        size: 1,
        start_address: 18,
    },
    PointDetails {
        point: |()| Point::Off9,
        size: 1,
        start_address: 19,
    },
    PointDetails {
        point: |()| Point::Val9,
        size: 1,
        start_address: 20,
    },
    PointDetails {
        point: |()| Point::Off10,
        size: 1,
        start_address: 21,
    },
    PointDetails {
        point: |()| Point::Val10,
        size: 1,
        start_address: 22,
    },
    PointDetails {
        point: |()| Point::Off11,
        size: 1,
        start_address: 23,
    },
    PointDetails {
        point: |()| Point::Val11,
        size: 1,
        start_address: 24,
    },
    PointDetails {
        point: |()| Point::Off12,
        size: 1,
        start_address: 25,
    },
    PointDetails {
        point: |()| Point::Val12,
        size: 1,
        start_address: 26,
    },
    PointDetails {
        point: |()| Point::Off13,
        size: 1,
        start_address: 27,
    },
    PointDetails {
        point: |()| Point::Val13,
        size: 1,
        start_address: 28,
    },
    PointDetails {
        point: |()| Point::Off14,
        size: 1,
        start_address: 29,
    },
    PointDetails {
        point: |()| Point::Val14,
        size: 1,
        start_address: 30,
    },
    PointDetails {
        point: |()| Point::Off15,
        size: 1,
        start_address: 31,
    },
    PointDetails {
        point: |()| Point::Val15,
        size: 1,
        start_address: 32,
    },
    PointDetails {
        point: |()| Point::Off16,
        size: 1,
        start_address: 33,
    },
    PointDetails {
        point: |()| Point::Val16,
        size: 1,
        start_address: 34,
    },
    PointDetails {
        point: |()| Point::Off17,
        size: 1,
        start_address: 35,
    },
    PointDetails {
        point: |()| Point::Val17,
        size: 1,
        start_address: 36,
    },
    PointDetails {
        point: |()| Point::Off18,
        size: 1,
        start_address: 37,
    },
    PointDetails {
        point: |()| Point::Val18,
        size: 1,
        start_address: 38,
    },
    PointDetails {
        point: |()| Point::Off19,
        size: 1,
        start_address: 39,
    },
    PointDetails {
        point: |()| Point::Val19,
        size: 1,
        start_address: 40,
    },
    PointDetails {
        point: |()| Point::Off20,
        size: 1,
        start_address: 41,
    },
    PointDetails {
        point: |()| Point::Val20,
        size: 1,
        start_address: 42,
    },
    PointDetails {
        point: |()| Point::Off21,
        size: 1,
        start_address: 43,
    },
    PointDetails {
        point: |()| Point::Val21,
        size: 1,
        start_address: 44,
    },
    PointDetails {
        point: |()| Point::Off22,
        size: 1,
        start_address: 45,
    },
    PointDetails {
        point: |()| Point::Val22,
        size: 1,
        start_address: 46,
    },
    PointDetails {
        point: |()| Point::Off23,
        size: 1,
        start_address: 47,
    },
    PointDetails {
        point: |()| Point::Val23,
        size: 1,
        start_address: 48,
    },
    PointDetails {
        point: |()| Point::Off24,
        size: 1,
        start_address: 49,
    },
    PointDetails {
        point: |()| Point::Val24,
        size: 1,
        start_address: 50,
    },
    PointDetails {
        point: |()| Point::Off25,
        size: 1,
        start_address: 51,
    },
    PointDetails {
        point: |()| Point::Val25,
        size: 1,
        start_address: 52,
    },
    PointDetails {
        point: |()| Point::Off26,
        size: 1,
        start_address: 53,
    },
    PointDetails {
        point: |()| Point::Val26,
        size: 1,
        start_address: 54,
    },
    PointDetails {
        point: |()| Point::Off27,
        size: 1,
        start_address: 55,
    },
    PointDetails {
        point: |()| Point::Val27,
        size: 1,
        start_address: 56,
    },
    PointDetails {
        point: |()| Point::Off28,
        size: 1,
        start_address: 57,
    },
    PointDetails {
        point: |()| Point::Val28,
        size: 1,
        start_address: 58,
    },
    PointDetails {
        point: |()| Point::Off29,
        size: 1,
        start_address: 59,
    },
    PointDetails {
        point: |()| Point::Val29,
        size: 1,
        start_address: 60,
    },
    PointDetails {
        point: |()| Point::Off30,
        size: 1,
        start_address: 61,
    },
    PointDetails {
        point: |()| Point::Val30,
        size: 1,
        start_address: 62,
    },
    PointDetails {
        point: |()| Point::Off31,
        size: 1,
        start_address: 63,
    },
    PointDetails {
        point: |()| Point::Val31,
        size: 1,
        start_address: 64,
    },
    PointDetails {
        point: |()| Point::Off32,
        size: 1,
        start_address: 65,
    },
    PointDetails {
        point: |()| Point::Val32,
        size: 1,
        start_address: 66,
    },
    PointDetails {
        point: |()| Point::Off33,
        size: 1,
        start_address: 67,
    },
    PointDetails {
        point: |()| Point::Val33,
        size: 1,
        start_address: 68,
    },
    PointDetails {
        point: |()| Point::Off34,
        size: 1,
        start_address: 69,
    },
    PointDetails {
        point: |()| Point::Val34,
        size: 1,
        start_address: 70,
    },
    PointDetails {
        point: |()| Point::Off35,
        size: 1,
        start_address: 71,
    },
    PointDetails {
        point: |()| Point::Val35,
        size: 1,
        start_address: 72,
    },
    PointDetails {
        point: |()| Point::Off36,
        size: 1,
        start_address: 73,
    },
    PointDetails {
        point: |()| Point::Val36,
        size: 1,
        start_address: 74,
    },
    PointDetails {
        point: |()| Point::Off37,
        size: 1,
        start_address: 75,
    },
    PointDetails {
        point: |()| Point::Val37,
        size: 1,
        start_address: 76,
    },
    PointDetails {
        point: |()| Point::Off38,
        size: 1,
        start_address: 77,
    },
    PointDetails {
        point: |()| Point::Val38,
        size: 1,
        start_address: 78,
    },
    PointDetails {
        point: |()| Point::Off39,
        size: 1,
        start_address: 79,
    },
    PointDetails {
        point: |()| Point::Val39,
        size: 1,
        start_address: 80,
    },
    PointDetails {
        point: |()| Point::Off40,
        size: 1,
        start_address: 81,
    },
    PointDetails {
        point: |()| Point::Val40,
        size: 1,
        start_address: 82,
    },
    PointDetails {
        point: |()| Point::Timestamp,
        size: 2,
        start_address: 83,
    },
    PointDetails {
        point: |()| Point::Milliseconds,
        size: 1,
        start_address: 85,
    },
    PointDetails {
        point: |()| Point::Sequence,
        size: 1,
        start_address: 86,
    },
    PointDetails {
        point: |()| Point::Role,
        size: 1,
        start_address: 87,
    },
    PointDetails {
        point: |()| Point::Algorithm,
        size: 1,
        start_address: 88,
    },
    PointDetails {
        point: |()| Point::N,
        size: 1,
        start_address: 89,
    },
];

static REPEATING_POINTS: [PointDetails<()>; 1] = [PointDetails {
    point: |()| Point::RepeatingDs,
    size: 1,
    start_address: 0,
}];

#[derive(Debug)]
pub enum Point {
    ModelId,
    ModelLength,
    X,
    Offset1,
    Value1,
    Off2,
    Val2,
    Off3,
    Val3,
    Off4,
    Val4,
    Off5,
    Val5,
    Off6,
    Val6,
    Off7,
    Val7,
    Off8,
    Val8,
    Off9,
    Val9,
    Off10,
    Val10,
    Off11,
    Val11,
    Off12,
    Val12,
    Off13,
    Val13,
    Off14,
    Val14,
    Off15,
    Val15,
    Off16,
    Val16,
    Off17,
    Val17,
    Off18,
    Val18,
    Off19,
    Val19,
    Off20,
    Val20,
    Off21,
    Val21,
    Off22,
    Val22,
    Off23,
    Val23,
    Off24,
    Val24,
    Off25,
    Val25,
    Off26,
    Val26,
    Off27,
    Val27,
    Off28,
    Val28,
    Off29,
    Val29,
    Off30,
    Val30,
    Off31,
    Val31,
    Off32,
    Val32,
    Off33,
    Val33,
    Off34,
    Val34,
    Off35,
    Val35,
    Off36,
    Val36,
    Off37,
    Val37,
    Off38,
    Val38,
    Off39,
    Val39,
    Off40,
    Val40,
    Timestamp,
    Milliseconds,
    Sequence,
    Role,
    Algorithm,
    N,
    RepeatingDs,
}

struct PointDetails<GroupIndexArgs> {
    point: fn(GroupIndexArgs) -> Point,
    start_address: u16,
    size: u16,
}

/// Marker for SunSpec model 5. Add it to a [`Sunspec`](crate::Sunspec) model list.
pub struct Model5;

impl<'ad> ModelSpec<'ad> for Model5 {
    const MODEL_ID: u16 = 5;
    type ReadAdapter = dyn ReadAdapter + 'ad;
    type WriteAdapter = dyn WriteAdapter + 'ad;

    fn model_length(&self) -> u16 {
        91
    }

    fn traverse_points_read<'a>(
        &self,
        adapter: Option<&Self::ReadAdapter>,
        buffer: &mut WritableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .chain(
                REPEATING_POINTS
                    .iter()
                    .map(move |p| (90 + p.start_address, p.size, (p.point)(()))),
            )
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            write_point_to_buffer(
                self,
                adapter,
                &point,
                &mut buffer.slice(cursor, word_count),
                point_offset,
            );
            cursor += word_count;
        }

        Ok(())
    }

    fn traverse_points_write<'a>(
        &self,
        adapter: &mut Self::WriteAdapter,
        buffer: &ReadableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .chain(
                REPEATING_POINTS
                    .iter()
                    .map(move |p| (90 + p.start_address, p.size, (p.point)(()))),
            )
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            if point_offset > 0 {
                return Err(ModbusException::IllegalDataAddress);
            }
            read_point_from_buffer(self, adapter, &point, &buffer.slice(cursor, word_count))?;
            cursor += word_count;
        }

        Ok(())
    }
}

pub(crate) fn write_point_to_buffer<'a>(
    model: &Model5,
    adapter: Option<&dyn ReadAdapter>,
    point: &Point,
    buffer: &mut WritableRegisterBuffer<'a>,
    offset: u16,
) {
    match point {
        Point::ModelId => {
            buffer.write_u16(5);
        }
        Point::ModelLength => {
            buffer.write_u16(model.model_length() - 2);
        }
        Point::X => {
            if let Some(value) = adapter.map(|adapter| adapter.x()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Offset1 => {
            if let Some(value) = adapter.map(|adapter| adapter.offset1()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Value1 => {
            if let Some(value) = adapter.map(|adapter| adapter.value1()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off2 => {
            if let Some(value) = adapter.map(|adapter| adapter.off2()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val2 => {
            if let Some(value) = adapter.map(|adapter| adapter.val2()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off3 => {
            if let Some(value) = adapter.map(|adapter| adapter.off3()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val3 => {
            if let Some(value) = adapter.map(|adapter| adapter.val3()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off4 => {
            if let Some(value) = adapter.map(|adapter| adapter.off4()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val4 => {
            if let Some(value) = adapter.map(|adapter| adapter.val4()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off5 => {
            if let Some(value) = adapter.map(|adapter| adapter.off5()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val5 => {
            if let Some(value) = adapter.map(|adapter| adapter.val5()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off6 => {
            if let Some(value) = adapter.map(|adapter| adapter.off6()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val6 => {
            if let Some(value) = adapter.map(|adapter| adapter.val6()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off7 => {
            if let Some(value) = adapter.map(|adapter| adapter.off7()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val7 => {
            if let Some(value) = adapter.map(|adapter| adapter.val7()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off8 => {
            if let Some(value) = adapter.map(|adapter| adapter.off8()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val8 => {
            if let Some(value) = adapter.map(|adapter| adapter.val8()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off9 => {
            if let Some(value) = adapter.map(|adapter| adapter.off9()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val9 => {
            if let Some(value) = adapter.map(|adapter| adapter.val9()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off10 => {
            if let Some(value) = adapter.map(|adapter| adapter.off10()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val10 => {
            if let Some(value) = adapter.map(|adapter| adapter.val10()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off11 => {
            if let Some(value) = adapter.map(|adapter| adapter.off11()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val11 => {
            if let Some(value) = adapter.map(|adapter| adapter.val11()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off12 => {
            if let Some(value) = adapter.map(|adapter| adapter.off12()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val12 => {
            if let Some(value) = adapter.map(|adapter| adapter.val12()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off13 => {
            if let Some(value) = adapter.map(|adapter| adapter.off13()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val13 => {
            if let Some(value) = adapter.map(|adapter| adapter.val13()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off14 => {
            if let Some(value) = adapter.map(|adapter| adapter.off14()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val14 => {
            if let Some(value) = adapter.map(|adapter| adapter.val14()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off15 => {
            if let Some(value) = adapter.map(|adapter| adapter.off15()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val15 => {
            if let Some(value) = adapter.map(|adapter| adapter.val15()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off16 => {
            if let Some(value) = adapter.map(|adapter| adapter.off16()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val16 => {
            if let Some(value) = adapter.map(|adapter| adapter.val16()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off17 => {
            if let Some(value) = adapter.map(|adapter| adapter.off17()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val17 => {
            if let Some(value) = adapter.map(|adapter| adapter.val17()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off18 => {
            if let Some(value) = adapter.map(|adapter| adapter.off18()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val18 => {
            if let Some(value) = adapter.map(|adapter| adapter.val18()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off19 => {
            if let Some(value) = adapter.map(|adapter| adapter.off19()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val19 => {
            if let Some(value) = adapter.map(|adapter| adapter.val19()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off20 => {
            if let Some(value) = adapter.map(|adapter| adapter.off20()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val20 => {
            if let Some(value) = adapter.map(|adapter| adapter.val20()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off21 => {
            if let Some(value) = adapter.map(|adapter| adapter.off21()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val21 => {
            if let Some(value) = adapter.map(|adapter| adapter.val21()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off22 => {
            if let Some(value) = adapter.map(|adapter| adapter.off22()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val22 => {
            if let Some(value) = adapter.map(|adapter| adapter.val22()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off23 => {
            if let Some(value) = adapter.map(|adapter| adapter.off23()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val23 => {
            if let Some(value) = adapter.map(|adapter| adapter.val23()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off24 => {
            if let Some(value) = adapter.map(|adapter| adapter.off24()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val24 => {
            if let Some(value) = adapter.map(|adapter| adapter.val24()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off25 => {
            if let Some(value) = adapter.map(|adapter| adapter.off25()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val25 => {
            if let Some(value) = adapter.map(|adapter| adapter.val25()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off26 => {
            if let Some(value) = adapter.map(|adapter| adapter.off26()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val26 => {
            if let Some(value) = adapter.map(|adapter| adapter.val26()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off27 => {
            if let Some(value) = adapter.map(|adapter| adapter.off27()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val27 => {
            if let Some(value) = adapter.map(|adapter| adapter.val27()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off28 => {
            if let Some(value) = adapter.map(|adapter| adapter.off28()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val28 => {
            if let Some(value) = adapter.map(|adapter| adapter.val28()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off29 => {
            if let Some(value) = adapter.map(|adapter| adapter.off29()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val29 => {
            if let Some(value) = adapter.map(|adapter| adapter.val29()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off30 => {
            if let Some(value) = adapter.map(|adapter| adapter.off30()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val30 => {
            if let Some(value) = adapter.map(|adapter| adapter.val30()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off31 => {
            if let Some(value) = adapter.map(|adapter| adapter.off31()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val31 => {
            if let Some(value) = adapter.map(|adapter| adapter.val31()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off32 => {
            if let Some(value) = adapter.map(|adapter| adapter.off32()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val32 => {
            if let Some(value) = adapter.map(|adapter| adapter.val32()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off33 => {
            if let Some(value) = adapter.map(|adapter| adapter.off33()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val33 => {
            if let Some(value) = adapter.map(|adapter| adapter.val33()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off34 => {
            if let Some(value) = adapter.map(|adapter| adapter.off34()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val34 => {
            if let Some(value) = adapter.map(|adapter| adapter.val34()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off35 => {
            if let Some(value) = adapter.map(|adapter| adapter.off35()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val35 => {
            if let Some(value) = adapter.map(|adapter| adapter.val35()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off36 => {
            if let Some(value) = adapter.map(|adapter| adapter.off36()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val36 => {
            if let Some(value) = adapter.map(|adapter| adapter.val36()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off37 => {
            if let Some(value) = adapter.map(|adapter| adapter.off37()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val37 => {
            if let Some(value) = adapter.map(|adapter| adapter.val37()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off38 => {
            if let Some(value) = adapter.map(|adapter| adapter.off38()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val38 => {
            if let Some(value) = adapter.map(|adapter| adapter.val38()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off39 => {
            if let Some(value) = adapter.map(|adapter| adapter.off39()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val39 => {
            if let Some(value) = adapter.map(|adapter| adapter.val39()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Off40 => {
            if let Some(value) = adapter.map(|adapter| adapter.off40()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val40 => {
            if let Some(value) = adapter.map(|adapter| adapter.val40()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Timestamp => {
            if let Some(value) = adapter.map(|adapter| adapter.timestamp()) {
                buffer.write_u32(value, offset);
            } else {
                buffer.write_u32(crate::not_implemented::UINT32, offset);
            }
        }
        Point::Milliseconds => {
            if let Some(value) = adapter.map(|adapter| adapter.milliseconds()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Sequence => {
            if let Some(value) = adapter.map(|adapter| adapter.sequence()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Role => {
            if let Some(value) = adapter.map(|adapter| adapter.role()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Algorithm => {
            if let Some(value) = adapter.map(|adapter| adapter.algorithm()) {
                buffer.write_u16(value as u16);
            } else {
                buffer.write_u16(crate::not_implemented::ENUM16);
            }
        }
        Point::N => {
            if let Some(value) = adapter.map(|adapter| adapter.n()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::RepeatingDs => {
            if let Some(value) = adapter.map(|adapter| adapter.repeating_ds()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
    }
}

pub(crate) fn read_point_from_buffer<'a>(
    model: &Model5,
    adapter: &mut dyn WriteAdapter,
    point: &Point,
    buffer: &ReadableRegisterBuffer<'a>,
) -> Result<(), ModbusException> {
    match point {
        Point::X => {
            let value = buffer.read_u16()?;
            adapter.set_x(value);
            Ok(())
        }
        Point::Offset1 => {
            let value = buffer.read_u16()?;
            adapter.set_offset1(value);
            Ok(())
        }
        Point::Value1 => {
            let value = buffer.read_u16()?;
            adapter.set_value1(value);
            Ok(())
        }
        Point::Off2 => {
            let value = buffer.read_u16()?;
            adapter.set_off2(value);
            Ok(())
        }
        Point::Val2 => {
            let value = buffer.read_u16()?;
            adapter.set_val2(value);
            Ok(())
        }
        Point::Off3 => {
            let value = buffer.read_u16()?;
            adapter.set_off3(value);
            Ok(())
        }
        Point::Val3 => {
            let value = buffer.read_u16()?;
            adapter.set_val3(value);
            Ok(())
        }
        Point::Off4 => {
            let value = buffer.read_u16()?;
            adapter.set_off4(value);
            Ok(())
        }
        Point::Val4 => {
            let value = buffer.read_u16()?;
            adapter.set_val4(value);
            Ok(())
        }
        Point::Off5 => {
            let value = buffer.read_u16()?;
            adapter.set_off5(value);
            Ok(())
        }
        Point::Val5 => {
            let value = buffer.read_u16()?;
            adapter.set_val5(value);
            Ok(())
        }
        Point::Off6 => {
            let value = buffer.read_u16()?;
            adapter.set_off6(value);
            Ok(())
        }
        Point::Val6 => {
            let value = buffer.read_u16()?;
            adapter.set_val6(value);
            Ok(())
        }
        Point::Off7 => {
            let value = buffer.read_u16()?;
            adapter.set_off7(value);
            Ok(())
        }
        Point::Val7 => {
            let value = buffer.read_u16()?;
            adapter.set_val7(value);
            Ok(())
        }
        Point::Off8 => {
            let value = buffer.read_u16()?;
            adapter.set_off8(value);
            Ok(())
        }
        Point::Val8 => {
            let value = buffer.read_u16()?;
            adapter.set_val8(value);
            Ok(())
        }
        Point::Off9 => {
            let value = buffer.read_u16()?;
            adapter.set_off9(value);
            Ok(())
        }
        Point::Val9 => {
            let value = buffer.read_u16()?;
            adapter.set_val9(value);
            Ok(())
        }
        Point::Off10 => {
            let value = buffer.read_u16()?;
            adapter.set_off10(value);
            Ok(())
        }
        Point::Val10 => {
            let value = buffer.read_u16()?;
            adapter.set_val10(value);
            Ok(())
        }
        Point::Off11 => {
            let value = buffer.read_u16()?;
            adapter.set_off11(value);
            Ok(())
        }
        Point::Val11 => {
            let value = buffer.read_u16()?;
            adapter.set_val11(value);
            Ok(())
        }
        Point::Off12 => {
            let value = buffer.read_u16()?;
            adapter.set_off12(value);
            Ok(())
        }
        Point::Val12 => {
            let value = buffer.read_u16()?;
            adapter.set_val12(value);
            Ok(())
        }
        Point::Off13 => {
            let value = buffer.read_u16()?;
            adapter.set_off13(value);
            Ok(())
        }
        Point::Val13 => {
            let value = buffer.read_u16()?;
            adapter.set_val13(value);
            Ok(())
        }
        Point::Off14 => {
            let value = buffer.read_u16()?;
            adapter.set_off14(value);
            Ok(())
        }
        Point::Val14 => {
            let value = buffer.read_u16()?;
            adapter.set_val14(value);
            Ok(())
        }
        Point::Off15 => {
            let value = buffer.read_u16()?;
            adapter.set_off15(value);
            Ok(())
        }
        Point::Val15 => {
            let value = buffer.read_u16()?;
            adapter.set_val15(value);
            Ok(())
        }
        Point::Off16 => {
            let value = buffer.read_u16()?;
            adapter.set_off16(value);
            Ok(())
        }
        Point::Val16 => {
            let value = buffer.read_u16()?;
            adapter.set_val16(value);
            Ok(())
        }
        Point::Off17 => {
            let value = buffer.read_u16()?;
            adapter.set_off17(value);
            Ok(())
        }
        Point::Val17 => {
            let value = buffer.read_u16()?;
            adapter.set_val17(value);
            Ok(())
        }
        Point::Off18 => {
            let value = buffer.read_u16()?;
            adapter.set_off18(value);
            Ok(())
        }
        Point::Val18 => {
            let value = buffer.read_u16()?;
            adapter.set_val18(value);
            Ok(())
        }
        Point::Off19 => {
            let value = buffer.read_u16()?;
            adapter.set_off19(value);
            Ok(())
        }
        Point::Val19 => {
            let value = buffer.read_u16()?;
            adapter.set_val19(value);
            Ok(())
        }
        Point::Off20 => {
            let value = buffer.read_u16()?;
            adapter.set_off20(value);
            Ok(())
        }
        Point::Val20 => {
            let value = buffer.read_u16()?;
            adapter.set_val20(value);
            Ok(())
        }
        Point::Off21 => {
            let value = buffer.read_u16()?;
            adapter.set_off21(value);
            Ok(())
        }
        Point::Val21 => {
            let value = buffer.read_u16()?;
            adapter.set_val21(value);
            Ok(())
        }
        Point::Off22 => {
            let value = buffer.read_u16()?;
            adapter.set_off22(value);
            Ok(())
        }
        Point::Val22 => {
            let value = buffer.read_u16()?;
            adapter.set_val22(value);
            Ok(())
        }
        Point::Off23 => {
            let value = buffer.read_u16()?;
            adapter.set_off23(value);
            Ok(())
        }
        Point::Val23 => {
            let value = buffer.read_u16()?;
            adapter.set_val23(value);
            Ok(())
        }
        Point::Off24 => {
            let value = buffer.read_u16()?;
            adapter.set_off24(value);
            Ok(())
        }
        Point::Val24 => {
            let value = buffer.read_u16()?;
            adapter.set_val24(value);
            Ok(())
        }
        Point::Off25 => {
            let value = buffer.read_u16()?;
            adapter.set_off25(value);
            Ok(())
        }
        Point::Val25 => {
            let value = buffer.read_u16()?;
            adapter.set_val25(value);
            Ok(())
        }
        Point::Off26 => {
            let value = buffer.read_u16()?;
            adapter.set_off26(value);
            Ok(())
        }
        Point::Val26 => {
            let value = buffer.read_u16()?;
            adapter.set_val26(value);
            Ok(())
        }
        Point::Off27 => {
            let value = buffer.read_u16()?;
            adapter.set_off27(value);
            Ok(())
        }
        Point::Val27 => {
            let value = buffer.read_u16()?;
            adapter.set_val27(value);
            Ok(())
        }
        Point::Off28 => {
            let value = buffer.read_u16()?;
            adapter.set_off28(value);
            Ok(())
        }
        Point::Val28 => {
            let value = buffer.read_u16()?;
            adapter.set_val28(value);
            Ok(())
        }
        Point::Off29 => {
            let value = buffer.read_u16()?;
            adapter.set_off29(value);
            Ok(())
        }
        Point::Val29 => {
            let value = buffer.read_u16()?;
            adapter.set_val29(value);
            Ok(())
        }
        Point::Off30 => {
            let value = buffer.read_u16()?;
            adapter.set_off30(value);
            Ok(())
        }
        Point::Val30 => {
            let value = buffer.read_u16()?;
            adapter.set_val30(value);
            Ok(())
        }
        Point::Off31 => {
            let value = buffer.read_u16()?;
            adapter.set_off31(value);
            Ok(())
        }
        Point::Val31 => {
            let value = buffer.read_u16()?;
            adapter.set_val31(value);
            Ok(())
        }
        Point::Off32 => {
            let value = buffer.read_u16()?;
            adapter.set_off32(value);
            Ok(())
        }
        Point::Val32 => {
            let value = buffer.read_u16()?;
            adapter.set_val32(value);
            Ok(())
        }
        Point::Off33 => {
            let value = buffer.read_u16()?;
            adapter.set_off33(value);
            Ok(())
        }
        Point::Val33 => {
            let value = buffer.read_u16()?;
            adapter.set_val33(value);
            Ok(())
        }
        Point::Off34 => {
            let value = buffer.read_u16()?;
            adapter.set_off34(value);
            Ok(())
        }
        Point::Val34 => {
            let value = buffer.read_u16()?;
            adapter.set_val34(value);
            Ok(())
        }
        Point::Off35 => {
            let value = buffer.read_u16()?;
            adapter.set_off35(value);
            Ok(())
        }
        Point::Val35 => {
            let value = buffer.read_u16()?;
            adapter.set_val35(value);
            Ok(())
        }
        Point::Off36 => {
            let value = buffer.read_u16()?;
            adapter.set_off36(value);
            Ok(())
        }
        Point::Val36 => {
            let value = buffer.read_u16()?;
            adapter.set_val36(value);
            Ok(())
        }
        Point::Off37 => {
            let value = buffer.read_u16()?;
            adapter.set_off37(value);
            Ok(())
        }
        Point::Val37 => {
            let value = buffer.read_u16()?;
            adapter.set_val37(value);
            Ok(())
        }
        Point::Off38 => {
            let value = buffer.read_u16()?;
            adapter.set_off38(value);
            Ok(())
        }
        Point::Val38 => {
            let value = buffer.read_u16()?;
            adapter.set_val38(value);
            Ok(())
        }
        Point::Off39 => {
            let value = buffer.read_u16()?;
            adapter.set_off39(value);
            Ok(())
        }
        Point::Val39 => {
            let value = buffer.read_u16()?;
            adapter.set_val39(value);
            Ok(())
        }
        Point::Off40 => {
            let value = buffer.read_u16()?;
            adapter.set_off40(value);
            Ok(())
        }
        Point::Val40 => {
            let value = buffer.read_u16()?;
            adapter.set_val40(value);
            Ok(())
        }
        Point::Timestamp => {
            let value = buffer.read_u32()?;
            adapter.set_timestamp(value);
            Ok(())
        }
        Point::Milliseconds => {
            let value = buffer.read_u16()?;
            adapter.set_milliseconds(value);
            Ok(())
        }
        Point::Sequence => {
            let value = buffer.read_u16()?;
            adapter.set_sequence(value);
            Ok(())
        }
        Point::Role => {
            let value = buffer.read_u16()?;
            adapter.set_role(value);
            Ok(())
        }
        Point::Algorithm => {
            let value = buffer.read_u16()?;
            let enum_value = Alg::from_repr(value).ok_or(ModbusException::IllegalDataValue)?;
            adapter.set_algorithm(enum_value);
            Ok(())
        }
        Point::N => {
            let value = buffer.read_u16()?;
            adapter.set_n(value);
            Ok(())
        }
        Point::RepeatingDs => {
            let value = buffer.read_u16()?;
            adapter.set_repeating_ds(value);
            Ok(())
        }
        _ => Err(ModbusException::IllegalDataAddress),
    }
}

pub trait ReadAdapter {
    /// X (X)
    ///
    /// Number of (offset, value) pairs being written
    ///
    /// A max of 50 (offset, value) pairs are allocated
    fn x(&self) -> u16;

    /// Offset1 (Off1)
    ///
    /// Offset of control register to write value to
    fn offset1(&self) -> u16;

    /// Value1 (Val1)
    ///
    /// Value to write to control register at offset
    fn value1(&self) -> u16;

    /// Off2
    fn off2(&self) -> u16;

    /// Val2
    fn val2(&self) -> u16;

    /// Off3
    fn off3(&self) -> u16;

    /// Val3
    fn val3(&self) -> u16;

    /// Off4
    fn off4(&self) -> u16;

    /// Val4
    fn val4(&self) -> u16;

    /// Off5
    fn off5(&self) -> u16;

    /// Val5
    fn val5(&self) -> u16;

    /// Off6
    fn off6(&self) -> u16;

    /// Val6
    fn val6(&self) -> u16;

    /// Off7
    fn off7(&self) -> u16;

    /// Val7
    fn val7(&self) -> u16;

    /// Off8
    fn off8(&self) -> u16;

    /// Val8
    fn val8(&self) -> u16;

    /// Off9
    fn off9(&self) -> u16;

    /// Val9
    fn val9(&self) -> u16;

    /// Off10
    fn off10(&self) -> u16;

    /// Val10
    fn val10(&self) -> u16;

    /// Off11
    fn off11(&self) -> u16;

    /// Val11
    fn val11(&self) -> u16;

    /// Off12
    fn off12(&self) -> u16;

    /// Val12
    fn val12(&self) -> u16;

    /// Off13
    fn off13(&self) -> u16;

    /// Val13
    fn val13(&self) -> u16;

    /// Off14
    fn off14(&self) -> u16;

    /// Val14
    fn val14(&self) -> u16;

    /// Off15
    fn off15(&self) -> u16;

    /// Val15
    fn val15(&self) -> u16;

    /// Off16
    fn off16(&self) -> u16;

    /// Val16
    fn val16(&self) -> u16;

    /// Off17
    fn off17(&self) -> u16;

    /// Val17
    fn val17(&self) -> u16;

    /// Off18
    fn off18(&self) -> u16;

    /// Val18
    fn val18(&self) -> u16;

    /// Off19
    fn off19(&self) -> u16;

    /// Val19
    fn val19(&self) -> u16;

    /// Off20
    fn off20(&self) -> u16;

    /// Val20
    fn val20(&self) -> u16;

    /// Off21
    fn off21(&self) -> u16;

    /// Val21
    fn val21(&self) -> u16;

    /// Off22
    fn off22(&self) -> u16;

    /// Val22
    fn val22(&self) -> u16;

    /// Off23
    fn off23(&self) -> u16;

    /// Val23
    fn val23(&self) -> u16;

    /// Off24
    fn off24(&self) -> u16;

    /// Val24
    fn val24(&self) -> u16;

    /// Off25
    fn off25(&self) -> u16;

    /// Val25
    fn val25(&self) -> u16;

    /// Off26
    fn off26(&self) -> u16;

    /// Val26
    fn val26(&self) -> u16;

    /// Off27
    fn off27(&self) -> u16;

    /// Val27
    fn val27(&self) -> u16;

    /// Off28
    fn off28(&self) -> u16;

    /// Val28
    fn val28(&self) -> u16;

    /// Off29
    fn off29(&self) -> u16;

    /// Val29
    fn val29(&self) -> u16;

    /// Off30
    fn off30(&self) -> u16;

    /// Val30
    fn val30(&self) -> u16;

    /// Off31
    fn off31(&self) -> u16;

    /// Val31
    fn val31(&self) -> u16;

    /// Off32
    fn off32(&self) -> u16;

    /// Val32
    fn val32(&self) -> u16;

    /// Off33
    fn off33(&self) -> u16;

    /// Val33
    fn val33(&self) -> u16;

    /// Off34
    fn off34(&self) -> u16;

    /// Val34
    fn val34(&self) -> u16;

    /// Off35
    fn off35(&self) -> u16;

    /// Val35
    fn val35(&self) -> u16;

    /// Off36
    fn off36(&self) -> u16;

    /// Val36
    fn val36(&self) -> u16;

    /// Off37
    fn off37(&self) -> u16;

    /// Val37
    fn val37(&self) -> u16;

    /// Off38
    fn off38(&self) -> u16;

    /// Val38
    fn val38(&self) -> u16;

    /// Off39
    fn off39(&self) -> u16;

    /// Val39
    fn val39(&self) -> u16;

    /// Off40
    fn off40(&self) -> u16;

    /// Val40
    fn val40(&self) -> u16;

    /// Timestamp (Ts)
    ///
    /// Timestamp value is the number of seconds since January 1, 2000
    fn timestamp(&self) -> u32;

    /// Milliseconds (Ms)
    ///
    /// Millisecond counter 0-999
    fn milliseconds(&self) -> u16;

    /// Sequence (Seq)
    ///
    /// Sequence number of request
    ///
    /// Shall be advanced for each request
    fn sequence(&self) -> u16;

    /// Role (Role)
    ///
    /// Signing key used 0-5
    ///
    /// Each controller is assigned a key index that maps to their access control role
    fn role(&self) -> u16;

    /// Algorithm (Alg)
    ///
    /// Algorithm used to compute the digital signature
    ///
    /// For future proof
    fn algorithm(&self) -> Alg;

    /// N (N)
    ///
    /// Number of registers comprising the digital signature.
    ///
    /// The value of N must be at least 4 (64 bits)
    fn n(&self) -> u16;

    /// DS (DS)
    ///
    /// Digital Signature
    fn repeating_ds(&self) -> u16;
}

pub trait WriteAdapter {
    /// X (X)
    ///
    /// Number of (offset, value) pairs being written
    ///
    /// A max of 50 (offset, value) pairs are allocated
    fn set_x(&mut self, value: u16);

    /// Offset1 (Off1)
    ///
    /// Offset of control register to write value to
    fn set_offset1(&mut self, value: u16);

    /// Value1 (Val1)
    ///
    /// Value to write to control register at offset
    fn set_value1(&mut self, value: u16);

    /// Off2
    fn set_off2(&mut self, value: u16);

    /// Val2
    fn set_val2(&mut self, value: u16);

    /// Off3
    fn set_off3(&mut self, value: u16);

    /// Val3
    fn set_val3(&mut self, value: u16);

    /// Off4
    fn set_off4(&mut self, value: u16);

    /// Val4
    fn set_val4(&mut self, value: u16);

    /// Off5
    fn set_off5(&mut self, value: u16);

    /// Val5
    fn set_val5(&mut self, value: u16);

    /// Off6
    fn set_off6(&mut self, value: u16);

    /// Val6
    fn set_val6(&mut self, value: u16);

    /// Off7
    fn set_off7(&mut self, value: u16);

    /// Val7
    fn set_val7(&mut self, value: u16);

    /// Off8
    fn set_off8(&mut self, value: u16);

    /// Val8
    fn set_val8(&mut self, value: u16);

    /// Off9
    fn set_off9(&mut self, value: u16);

    /// Val9
    fn set_val9(&mut self, value: u16);

    /// Off10
    fn set_off10(&mut self, value: u16);

    /// Val10
    fn set_val10(&mut self, value: u16);

    /// Off11
    fn set_off11(&mut self, value: u16);

    /// Val11
    fn set_val11(&mut self, value: u16);

    /// Off12
    fn set_off12(&mut self, value: u16);

    /// Val12
    fn set_val12(&mut self, value: u16);

    /// Off13
    fn set_off13(&mut self, value: u16);

    /// Val13
    fn set_val13(&mut self, value: u16);

    /// Off14
    fn set_off14(&mut self, value: u16);

    /// Val14
    fn set_val14(&mut self, value: u16);

    /// Off15
    fn set_off15(&mut self, value: u16);

    /// Val15
    fn set_val15(&mut self, value: u16);

    /// Off16
    fn set_off16(&mut self, value: u16);

    /// Val16
    fn set_val16(&mut self, value: u16);

    /// Off17
    fn set_off17(&mut self, value: u16);

    /// Val17
    fn set_val17(&mut self, value: u16);

    /// Off18
    fn set_off18(&mut self, value: u16);

    /// Val18
    fn set_val18(&mut self, value: u16);

    /// Off19
    fn set_off19(&mut self, value: u16);

    /// Val19
    fn set_val19(&mut self, value: u16);

    /// Off20
    fn set_off20(&mut self, value: u16);

    /// Val20
    fn set_val20(&mut self, value: u16);

    /// Off21
    fn set_off21(&mut self, value: u16);

    /// Val21
    fn set_val21(&mut self, value: u16);

    /// Off22
    fn set_off22(&mut self, value: u16);

    /// Val22
    fn set_val22(&mut self, value: u16);

    /// Off23
    fn set_off23(&mut self, value: u16);

    /// Val23
    fn set_val23(&mut self, value: u16);

    /// Off24
    fn set_off24(&mut self, value: u16);

    /// Val24
    fn set_val24(&mut self, value: u16);

    /// Off25
    fn set_off25(&mut self, value: u16);

    /// Val25
    fn set_val25(&mut self, value: u16);

    /// Off26
    fn set_off26(&mut self, value: u16);

    /// Val26
    fn set_val26(&mut self, value: u16);

    /// Off27
    fn set_off27(&mut self, value: u16);

    /// Val27
    fn set_val27(&mut self, value: u16);

    /// Off28
    fn set_off28(&mut self, value: u16);

    /// Val28
    fn set_val28(&mut self, value: u16);

    /// Off29
    fn set_off29(&mut self, value: u16);

    /// Val29
    fn set_val29(&mut self, value: u16);

    /// Off30
    fn set_off30(&mut self, value: u16);

    /// Val30
    fn set_val30(&mut self, value: u16);

    /// Off31
    fn set_off31(&mut self, value: u16);

    /// Val31
    fn set_val31(&mut self, value: u16);

    /// Off32
    fn set_off32(&mut self, value: u16);

    /// Val32
    fn set_val32(&mut self, value: u16);

    /// Off33
    fn set_off33(&mut self, value: u16);

    /// Val33
    fn set_val33(&mut self, value: u16);

    /// Off34
    fn set_off34(&mut self, value: u16);

    /// Val34
    fn set_val34(&mut self, value: u16);

    /// Off35
    fn set_off35(&mut self, value: u16);

    /// Val35
    fn set_val35(&mut self, value: u16);

    /// Off36
    fn set_off36(&mut self, value: u16);

    /// Val36
    fn set_val36(&mut self, value: u16);

    /// Off37
    fn set_off37(&mut self, value: u16);

    /// Val37
    fn set_val37(&mut self, value: u16);

    /// Off38
    fn set_off38(&mut self, value: u16);

    /// Val38
    fn set_val38(&mut self, value: u16);

    /// Off39
    fn set_off39(&mut self, value: u16);

    /// Val39
    fn set_val39(&mut self, value: u16);

    /// Off40
    fn set_off40(&mut self, value: u16);

    /// Val40
    fn set_val40(&mut self, value: u16);

    /// Timestamp (Ts)
    ///
    /// Timestamp value is the number of seconds since January 1, 2000
    fn set_timestamp(&mut self, value: u32);

    /// Milliseconds (Ms)
    ///
    /// Millisecond counter 0-999
    fn set_milliseconds(&mut self, value: u16);

    /// Sequence (Seq)
    ///
    /// Sequence number of request
    ///
    /// Shall be advanced for each request
    fn set_sequence(&mut self, value: u16);

    /// Role (Role)
    ///
    /// Signing key used 0-5
    ///
    /// Each controller is assigned a key index that maps to their access control role
    fn set_role(&mut self, value: u16);

    /// Algorithm (Alg)
    ///
    /// Algorithm used to compute the digital signature
    ///
    /// For future proof
    fn set_algorithm(&mut self, value: Alg);

    /// N (N)
    ///
    /// Number of registers comprising the digital signature.
    ///
    /// The value of N must be at least 4 (64 bits)
    fn set_n(&mut self, value: u16);

    /// DS (DS)
    ///
    /// Digital Signature
    fn set_repeating_ds(&mut self, value: u16);
}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model5Alg {
    /// For test purposes only
    None = 0,
    AesGmac64 = 1,
    Ecc256 = 2,
}

impl Model5Alg {
    pub fn from_repr(repr: u16) -> Option<Model5Alg> {
        match repr {
            0 => Some(Model5Alg::None),
            1 => Some(Model5Alg::AesGmac64),
            2 => Some(Model5Alg::Ecc256),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model5Alg`] - only `Model5Alg` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `Alg` distinct from another model's point of the same name.
pub type Alg = Model5Alg;
