// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use crate::{ModbusException, ModelSpec};
use core::cmp::min;

static POINTS: [PointDetails<()>; 25] = [
    PointDetails {
        point: |()| Point::ModelId,
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |()| Point::ModelLength,
        size: 1,
        start_address: 1,
    },
    PointDetails {
        point: |()| Point::PortNumber,
        size: 1,
        start_address: 2,
    },
    PointDetails {
        point: |()| Point::VSf,
        size: 1,
        start_address: 3,
    },
    PointDetails {
        point: |()| Point::ASf,
        size: 1,
        start_address: 4,
    },
    PointDetails {
        point: |()| Point::PSf,
        size: 1,
        start_address: 5,
    },
    PointDetails {
        point: |()| Point::AhSf,
        size: 1,
        start_address: 6,
    },
    PointDetails {
        point: |()| Point::KwhSf,
        size: 1,
        start_address: 7,
    },
    PointDetails {
        point: |()| Point::BatteryVoltage,
        size: 1,
        start_address: 8,
    },
    PointDetails {
        point: |()| Point::ArrayVoltage,
        size: 1,
        start_address: 9,
    },
    PointDetails {
        point: |()| Point::OutputCurrent,
        size: 1,
        start_address: 10,
    },
    PointDetails {
        point: |()| Point::ArrayCurrent,
        size: 1,
        start_address: 11,
    },
    PointDetails {
        point: |()| Point::OperatingState,
        size: 1,
        start_address: 12,
    },
    PointDetails {
        point: |()| Point::OutputWattage,
        size: 1,
        start_address: 13,
    },
    PointDetails {
        point: |()| Point::TodaySMinimumBatteryVoltage,
        size: 1,
        start_address: 14,
    },
    PointDetails {
        point: |()| Point::TodaySMaximumBatteryVoltage,
        size: 1,
        start_address: 15,
    },
    PointDetails {
        point: |()| Point::Voc,
        size: 1,
        start_address: 16,
    },
    PointDetails {
        point: |()| Point::TodaySMaximumVoc,
        size: 1,
        start_address: 17,
    },
    PointDetails {
        point: |()| Point::TodaySKWh,
        size: 1,
        start_address: 18,
    },
    PointDetails {
        point: |()| Point::TodaySAh,
        size: 1,
        start_address: 19,
    },
    PointDetails {
        point: |()| Point::LifetimeKWh,
        size: 1,
        start_address: 20,
    },
    PointDetails {
        point: |()| Point::LifetimeKAh,
        size: 1,
        start_address: 21,
    },
    PointDetails {
        point: |()| Point::LifetimeMaximumOutputWattage,
        size: 1,
        start_address: 22,
    },
    PointDetails {
        point: |()| Point::LifetimeMaximumBatteryVoltage,
        size: 1,
        start_address: 23,
    },
    PointDetails {
        point: |()| Point::LifetimeMaximumVocVoltage,
        size: 1,
        start_address: 24,
    },
];

#[derive(Debug)]
pub enum Point {
    ModelId,
    ModelLength,
    PortNumber,
    VSf,
    ASf,
    PSf,
    AhSf,
    KwhSf,
    BatteryVoltage,
    ArrayVoltage,
    OutputCurrent,
    ArrayCurrent,
    OperatingState,
    OutputWattage,
    TodaySMinimumBatteryVoltage,
    TodaySMaximumBatteryVoltage,
    Voc,
    TodaySMaximumVoc,
    TodaySKWh,
    TodaySAh,
    LifetimeKWh,
    LifetimeKAh,
    LifetimeMaximumOutputWattage,
    LifetimeMaximumBatteryVoltage,
    LifetimeMaximumVocVoltage,
}

struct PointDetails<GroupIndexArgs> {
    point: fn(GroupIndexArgs) -> Point,
    start_address: u16,
    size: u16,
}

/// Marker for SunSpec model 64111. Add it to a [`Sunspec`](crate::Sunspec) model list.
pub struct Model64111;

impl<'ad> ModelSpec<'ad> for Model64111 {
    const MODEL_ID: u16 = 64111;
    type ReadAdapter = dyn ReadAdapter + 'ad;
    type WriteAdapter = dyn WriteAdapter + 'ad;

    fn model_length(&self) -> u16 {
        25
    }

    fn traverse_points_read<'a>(
        &self,
        adapter: Option<&Self::ReadAdapter>,
        buffer: &mut WritableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            write_point_to_buffer(
                self,
                adapter,
                &point,
                &mut buffer.slice(cursor, word_count),
                point_offset,
            );
            cursor += word_count;
        }

        Ok(())
    }

    fn traverse_points_write<'a>(
        &self,
        adapter: &mut Self::WriteAdapter,
        buffer: &ReadableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            if point_offset > 0 {
                return Err(ModbusException::IllegalDataAddress);
            }
            read_point_from_buffer(self, adapter, &point, &buffer.slice(cursor, word_count))?;
            cursor += word_count;
        }

        Ok(())
    }
}

pub(crate) fn write_point_to_buffer<'a>(
    model: &Model64111,
    adapter: Option<&dyn ReadAdapter>,
    point: &Point,
    buffer: &mut WritableRegisterBuffer<'a>,
    offset: u16,
) {
    match point {
        Point::ModelId => {
            buffer.write_u16(64111);
        }
        Point::ModelLength => {
            buffer.write_u16(model.model_length() - 2);
        }
        Point::PortNumber => {
            if let Some(value) = adapter.map(|adapter| adapter.port_number()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::VSf => {
            if let Some(value) = adapter.map(|adapter| adapter.v_sf()) {
                buffer.write_i16(value);
            } else {
                buffer.write_i16(crate::not_implemented::SUNSSF);
            }
        }
        Point::ASf => {
            if let Some(value) = adapter.map(|adapter| adapter.a_sf()) {
                buffer.write_i16(value);
            } else {
                buffer.write_i16(crate::not_implemented::SUNSSF);
            }
        }
        Point::PSf => {
            if let Some(value) = adapter.map(|adapter| adapter.p_sf()) {
                buffer.write_i16(value);
            } else {
                buffer.write_i16(crate::not_implemented::SUNSSF);
            }
        }
        Point::AhSf => {
            if let Some(value) = adapter.map(|adapter| adapter.ah_sf()) {
                buffer.write_i16(value);
            } else {
                buffer.write_i16(crate::not_implemented::SUNSSF);
            }
        }
        Point::KwhSf => {
            if let Some(value) = adapter.map(|adapter| adapter.kwh_sf()) {
                buffer.write_i16(value);
            } else {
                buffer.write_i16(crate::not_implemented::SUNSSF);
            }
        }
        Point::BatteryVoltage => {
            if let Some(value) = adapter.map(|adapter| adapter.battery_voltage()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::ArrayVoltage => {
            if let Some(value) = adapter.map(|adapter| adapter.array_voltage()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::OutputCurrent => {
            if let Some(value) = adapter.map(|adapter| adapter.output_current()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::ArrayCurrent => {
            if let Some(value) = adapter.map(|adapter| adapter.array_current()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::OperatingState => {
            if let Some(value) = adapter.map(|adapter| adapter.operating_state()) {
                buffer.write_u16(value as u16);
            } else {
                buffer.write_u16(crate::not_implemented::ENUM16);
            }
        }
        Point::OutputWattage => {
            if let Some(value) = adapter.map(|adapter| adapter.output_wattage()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::TodaySMinimumBatteryVoltage => {
            if let Some(value) = adapter.map(|adapter| adapter.today_s_minimum_battery_voltage()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::TodaySMaximumBatteryVoltage => {
            if let Some(value) = adapter.map(|adapter| adapter.today_s_maximum_battery_voltage()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Voc => {
            if let Some(value) = adapter.map(|adapter| adapter.voc()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::TodaySMaximumVoc => {
            if let Some(value) = adapter.map(|adapter| adapter.today_s_maximum_voc()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::TodaySKWh => {
            if let Some(value) = adapter.map(|adapter| adapter.today_s_k_wh()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::TodaySAh => {
            if let Some(value) = adapter.map(|adapter| adapter.today_s_ah()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::LifetimeKWh => {
            if let Some(value) = adapter.map(|adapter| adapter.lifetime_k_wh()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::LifetimeKAh => {
            if let Some(value) = adapter.map(|adapter| adapter.lifetime_k_ah()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::LifetimeMaximumOutputWattage => {
            if let Some(value) = adapter.map(|adapter| adapter.lifetime_maximum_output_wattage()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::LifetimeMaximumBatteryVoltage => {
            if let Some(value) = adapter.map(|adapter| adapter.lifetime_maximum_battery_voltage()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::LifetimeMaximumVocVoltage => {
            if let Some(value) = adapter.map(|adapter| adapter.lifetime_maximum_voc_voltage()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
    }
}

pub(crate) fn read_point_from_buffer<'a>(
    model: &Model64111,
    adapter: &mut dyn WriteAdapter,
    point: &Point,
    buffer: &ReadableRegisterBuffer<'a>,
) -> Result<(), ModbusException> {
    Err(ModbusException::IllegalDataAddress)
}

pub trait ReadAdapter {
    /// Port Number (Port)
    fn port_number(&self) -> u16;

    /// V_SF
    fn v_sf(&self) -> i16;

    /// A_SF
    fn a_sf(&self) -> i16;

    /// P_SF
    fn p_sf(&self) -> i16;

    /// AH_SF
    fn ah_sf(&self) -> i16;

    /// KWH_SF
    fn kwh_sf(&self) -> i16;

    /// Battery Voltage (BattV)
    fn battery_voltage(&self) -> u16;

    /// Array Voltage (ArrayV)
    fn array_voltage(&self) -> u16;

    /// Output Current (OutputA)
    fn output_current(&self) -> u16;

    /// Array Current (InputA)
    fn array_current(&self) -> u16;

    /// Operating State (ChargerSt)
    fn operating_state(&self) -> ChargerSt;

    /// Output Wattage (OutputW)
    fn output_wattage(&self) -> u16;

    /// Today's Minimum Battery Voltage (TodayMinBatV)
    fn today_s_minimum_battery_voltage(&self) -> u16;

    /// Today's Maximum Battery Voltage (TodayMaxBatV)
    fn today_s_maximum_battery_voltage(&self) -> u16;

    /// VOC (VOCV)
    fn voc(&self) -> u16;

    /// Today's Maximum VOC (TodayMaxVOC)
    fn today_s_maximum_voc(&self) -> u16;

    /// Today's kWh (TodaykWhOutput)
    fn today_s_k_wh(&self) -> u16;

    /// Today's AH (TodayAHOutput)
    fn today_s_ah(&self) -> u16;

    /// Lifetime kWh (LifeTimeKWHOut)
    fn lifetime_k_wh(&self) -> u16;

    /// Lifetime kAH (LifeTimeAHOut)
    fn lifetime_k_ah(&self) -> u16;

    /// Lifetime Maximum Output Wattage (LifeTimeMaxOut)
    fn lifetime_maximum_output_wattage(&self) -> u16;

    /// Lifetime Maximum Battery Voltage (LifeTimeMaxBatt)
    fn lifetime_maximum_battery_voltage(&self) -> u16;

    /// Lifetime Maximum VOC Voltage (LifeTimeMaxVOC)
    fn lifetime_maximum_voc_voltage(&self) -> u16;
}

pub trait WriteAdapter {}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model64111ChargerSt {
    Off = 0,
    Float = 1,
    Bulk = 2,
    Absorb = 3,
    Eq = 4,
}

impl Model64111ChargerSt {
    pub fn from_repr(repr: u16) -> Option<Model64111ChargerSt> {
        match repr {
            0 => Some(Model64111ChargerSt::Off),
            1 => Some(Model64111ChargerSt::Float),
            2 => Some(Model64111ChargerSt::Bulk),
            3 => Some(Model64111ChargerSt::Absorb),
            4 => Some(Model64111ChargerSt::Eq),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model64111ChargerSt`] - only `Model64111ChargerSt` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `ChargerSt` distinct from another model's point of the same name.
pub type ChargerSt = Model64111ChargerSt;
