// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use crate::{ModbusException, ModelSpec};
use core::cmp::min;

static POINTS: [PointDetails<()>; 18] = [
    PointDetails {
        point: |()| Point::ModelId,
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |()| Point::ModelLength,
        size: 1,
        start_address: 1,
    },
    PointDetails {
        point: |()| Point::DcaSf,
        size: 1,
        start_address: 2,
    },
    PointDetails {
        point: |()| Point::DcAhrSf,
        size: 1,
        start_address: 3,
    },
    PointDetails {
        point: |()| Point::DcvSf,
        size: 1,
        start_address: 4,
    },
    PointDetails {
        point: |()| Point::DcwSf,
        size: 1,
        start_address: 5,
    },
    PointDetails {
        point: |()| Point::DcWhSf,
        size: 1,
        start_address: 6,
    },
    PointDetails {
        point: |()| Point::Rating,
        size: 1,
        start_address: 7,
    },
    PointDetails {
        point: |()| Point::N,
        size: 1,
        start_address: 8,
    },
    PointDetails {
        point: |()| Point::Event,
        size: 2,
        start_address: 9,
    },
    PointDetails {
        point: |()| Point::VendorEvent,
        size: 2,
        start_address: 11,
    },
    PointDetails {
        point: |()| Point::Amps,
        size: 1,
        start_address: 13,
    },
    PointDetails {
        point: |()| Point::AmpHours,
        size: 2,
        start_address: 14,
    },
    PointDetails {
        point: |()| Point::Voltage,
        size: 1,
        start_address: 16,
    },
    PointDetails {
        point: |()| Point::Temp,
        size: 1,
        start_address: 17,
    },
    PointDetails {
        point: |()| Point::Watts,
        size: 1,
        start_address: 18,
    },
    PointDetails {
        point: |()| Point::Pr,
        size: 1,
        start_address: 19,
    },
    PointDetails {
        point: |()| Point::WattHours,
        size: 2,
        start_address: 20,
    },
];

static STRING_POINTS: [PointDetails<()>; 10] = [
    PointDetails {
        point: |()| Point::StringId,
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |()| Point::StringInputEvent,
        size: 2,
        start_address: 1,
    },
    PointDetails {
        point: |()| Point::StringVendorEvent,
        size: 2,
        start_address: 3,
    },
    PointDetails {
        point: |()| Point::StringAmps,
        size: 1,
        start_address: 5,
    },
    PointDetails {
        point: |()| Point::StringAmpHours,
        size: 2,
        start_address: 6,
    },
    PointDetails {
        point: |()| Point::StringVoltage,
        size: 1,
        start_address: 8,
    },
    PointDetails {
        point: |()| Point::StringWatts,
        size: 1,
        start_address: 9,
    },
    PointDetails {
        point: |()| Point::StringWattHours,
        size: 2,
        start_address: 10,
    },
    PointDetails {
        point: |()| Point::StringPr,
        size: 1,
        start_address: 12,
    },
    PointDetails {
        point: |()| Point::StringN,
        size: 1,
        start_address: 13,
    },
];

#[derive(Debug)]
pub enum Point {
    ModelId,
    ModelLength,
    DcaSf,
    DcAhrSf,
    DcvSf,
    DcwSf,
    DcWhSf,
    Rating,
    N,
    Event,
    VendorEvent,
    Amps,
    AmpHours,
    Voltage,
    Temp,
    Watts,
    Pr,
    WattHours,
    StringId,
    StringInputEvent,
    StringVendorEvent,
    StringAmps,
    StringAmpHours,
    StringVoltage,
    StringWatts,
    StringWattHours,
    StringPr,
    StringN,
}

struct PointDetails<GroupIndexArgs> {
    point: fn(GroupIndexArgs) -> Point,
    start_address: u16,
    size: u16,
}

/// Marker for SunSpec model 402. Add it to a [`Sunspec`](crate::Sunspec) model list.
pub struct Model402;

impl<'ad> ModelSpec<'ad> for Model402 {
    const MODEL_ID: u16 = 402;
    type ReadAdapter = dyn ReadAdapter + 'ad;
    type WriteAdapter = dyn WriteAdapter + 'ad;

    fn model_length(&self) -> u16 {
        36
    }

    fn traverse_points_read<'a>(
        &self,
        adapter: Option<&Self::ReadAdapter>,
        buffer: &mut WritableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .chain(
                STRING_POINTS
                    .iter()
                    .map(move |p| (22 + p.start_address, p.size, (p.point)(()))),
            )
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            write_point_to_buffer(
                self,
                adapter,
                &point,
                &mut buffer.slice(cursor, word_count),
                point_offset,
            );
            cursor += word_count;
        }

        Ok(())
    }

    fn traverse_points_write<'a>(
        &self,
        adapter: &mut Self::WriteAdapter,
        buffer: &ReadableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .chain(
                STRING_POINTS
                    .iter()
                    .map(move |p| (22 + p.start_address, p.size, (p.point)(()))),
            )
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            if point_offset > 0 {
                return Err(ModbusException::IllegalDataAddress);
            }
            read_point_from_buffer(self, adapter, &point, &buffer.slice(cursor, word_count))?;
            cursor += word_count;
        }

        Ok(())
    }
}

pub(crate) fn write_point_to_buffer<'a>(
    model: &Model402,
    adapter: Option<&dyn ReadAdapter>,
    point: &Point,
    buffer: &mut WritableRegisterBuffer<'a>,
    offset: u16,
) {
    match point {
        Point::ModelId => {
            buffer.write_u16(402);
        }
        Point::ModelLength => {
            buffer.write_u16(model.model_length() - 2);
        }
        Point::DcaSf => {
            if let Some(value) = adapter.map(|adapter| adapter.dca_sf()) {
                buffer.write_i16(value);
            } else {
                buffer.write_i16(crate::not_implemented::SUNSSF);
            }
        }
        Point::DcAhrSf => {
            if let Some(value) = adapter.and_then(|adapter| adapter.dc_ahr_sf()) {
                buffer.write_i16(value);
            } else {
                buffer.write_i16(crate::not_implemented::SUNSSF);
            }
        }
        Point::DcvSf => {
            if let Some(value) = adapter.and_then(|adapter| adapter.dcv_sf()) {
                buffer.write_i16(value);
            } else {
                buffer.write_i16(crate::not_implemented::SUNSSF);
            }
        }
        Point::DcwSf => {
            if let Some(value) = adapter.and_then(|adapter| adapter.dcw_sf()) {
                buffer.write_i16(value);
            } else {
                buffer.write_i16(crate::not_implemented::SUNSSF);
            }
        }
        Point::DcWhSf => {
            if let Some(value) = adapter.map(|adapter| adapter.dc_wh_sf()) {
                buffer.write_i16(value);
            } else {
                buffer.write_i16(crate::not_implemented::SUNSSF);
            }
        }
        Point::Rating => {
            if let Some(value) = adapter.and_then(|adapter| adapter.rating()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::N => {
            if let Some(value) = adapter.and_then(|adapter| adapter.n()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::COUNT);
            }
        }
        Point::Event => {
            if let Some(value) = adapter.map(|adapter| adapter.event()) {
                buffer.write_u32(value, offset);
            } else {
                buffer.write_u32(crate::not_implemented::BITFIELD32, offset);
            }
        }
        Point::VendorEvent => {
            if let Some(value) = adapter.and_then(|adapter| adapter.vendor_event()) {
                buffer.write_u32(value, offset);
            } else {
                buffer.write_u32(crate::not_implemented::BITFIELD32, offset);
            }
        }
        Point::Amps => {
            if let Some(value) = adapter.map(|adapter| adapter.amps()) {
                buffer.write_i16(value);
            } else {
                buffer.write_i16(crate::not_implemented::INT16);
            }
        }
        Point::AmpHours => {
            if let Some(value) = adapter.and_then(|adapter| adapter.amp_hours()) {
                buffer.write_u32(value, offset);
            } else {
                buffer.write_u32(crate::not_implemented::UINT32, offset);
            }
        }
        Point::Voltage => {
            if let Some(value) = adapter.and_then(|adapter| adapter.voltage()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Temp => {
            if let Some(value) = adapter.and_then(|adapter| adapter.temp()) {
                buffer.write_i16(value);
            } else {
                buffer.write_i16(crate::not_implemented::INT16);
            }
        }
        Point::Watts => {
            if let Some(value) = adapter.and_then(|adapter| adapter.watts()) {
                buffer.write_i16(value);
            } else {
                buffer.write_i16(crate::not_implemented::INT16);
            }
        }
        Point::Pr => {
            if let Some(value) = adapter.and_then(|adapter| adapter.pr()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::WattHours => {
            if let Some(value) = adapter.map(|adapter| adapter.watt_hours()) {
                buffer.write_u32(value, offset);
            } else {
                buffer.write_u32(crate::not_implemented::UINT32, offset);
            }
        }
        Point::StringId => {
            if let Some(value) = adapter.map(|adapter| adapter.string_id()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::StringInputEvent => {
            if let Some(value) = adapter.map(|adapter| adapter.string_input_event()) {
                buffer.write_u32(value, offset);
            } else {
                buffer.write_u32(crate::not_implemented::BITFIELD32, offset);
            }
        }
        Point::StringVendorEvent => {
            if let Some(value) = adapter.and_then(|adapter| adapter.string_vendor_event()) {
                buffer.write_u32(value, offset);
            } else {
                buffer.write_u32(crate::not_implemented::BITFIELD32, offset);
            }
        }
        Point::StringAmps => {
            if let Some(value) = adapter.map(|adapter| adapter.string_amps()) {
                buffer.write_i16(value);
            } else {
                buffer.write_i16(crate::not_implemented::INT16);
            }
        }
        Point::StringAmpHours => {
            if let Some(value) = adapter.and_then(|adapter| adapter.string_amp_hours()) {
                buffer.write_u32(value, offset);
            } else {
                buffer.write_u32(crate::not_implemented::UINT32, offset);
            }
        }
        Point::StringVoltage => {
            if let Some(value) = adapter.and_then(|adapter| adapter.string_voltage()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::StringWatts => {
            if let Some(value) = adapter.and_then(|adapter| adapter.string_watts()) {
                buffer.write_i16(value);
            } else {
                buffer.write_i16(crate::not_implemented::INT16);
            }
        }
        Point::StringWattHours => {
            if let Some(value) = adapter.and_then(|adapter| adapter.string_watt_hours()) {
                buffer.write_u32(value, offset);
            } else {
                buffer.write_u32(crate::not_implemented::UINT32, offset);
            }
        }
        Point::StringPr => {
            if let Some(value) = adapter.and_then(|adapter| adapter.string_pr()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::StringN => {
            if let Some(value) = adapter.and_then(|adapter| adapter.string_n()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
    }
}

pub(crate) fn read_point_from_buffer<'a>(
    model: &Model402,
    adapter: &mut dyn WriteAdapter,
    point: &Point,
    buffer: &ReadableRegisterBuffer<'a>,
) -> Result<(), ModbusException> {
    Err(ModbusException::IllegalDataAddress)
}

pub trait ReadAdapter {
    /// DCA_SF
    ///
    /// Current scale factor
    fn dca_sf(&self) -> i16;

    /// DCAhr_SF
    ///
    /// Amp-hour scale factor
    fn dc_ahr_sf(&self) -> Option<i16> {
        None
    }

    /// DCV_SF
    ///
    /// Voltage scale factor
    fn dcv_sf(&self) -> Option<i16> {
        None
    }

    /// DCW_SF
    ///
    /// Power scale factor
    fn dcw_sf(&self) -> Option<i16> {
        None
    }

    /// DCWh_SF
    ///
    /// Energy scale factor
    fn dc_wh_sf(&self) -> i16;

    /// Rating (DCAMax)
    ///
    /// Maximum DC Current Rating
    fn rating(&self) -> Option<u16> {
        None
    }

    /// N (N)
    ///
    /// Number of Inputs
    fn n(&self) -> Option<u16> {
        None
    }

    /// Event (Evt)
    ///
    /// Events
    fn event(&self) -> u32;

    /// Vendor Event (EvtVnd)
    ///
    /// Vendor defined events
    fn vendor_event(&self) -> Option<u32> {
        None
    }

    /// Amps (DCA)
    ///
    /// Total measured current
    fn amps(&self) -> i16;

    /// Amp-hours (DCAhr)
    ///
    /// Total metered Amp-hours
    fn amp_hours(&self) -> Option<u32> {
        None
    }

    /// Voltage (DCV)
    ///
    /// Output Voltage
    fn voltage(&self) -> Option<u16> {
        None
    }

    /// Temp (Tmp)
    ///
    /// Internal operating temperature
    fn temp(&self) -> Option<i16> {
        None
    }

    /// Watts (DCW)
    ///
    /// Output power
    fn watts(&self) -> Option<i16> {
        None
    }

    /// PR (DCPR)
    ///
    /// DC Performance ratio value
    fn pr(&self) -> Option<u16> {
        None
    }

    /// Watt-hours (DCWh)
    ///
    /// Output energy
    fn watt_hours(&self) -> u32;

    /// ID (InID)
    ///
    /// Uniquely identifies this input set
    fn string_id(&self) -> u16;

    /// Input Event (InEvt)
    ///
    /// String Input Event Flags
    fn string_input_event(&self) -> u32;

    /// Vendor Event (EvtVnd)
    ///
    /// Vendor defined events
    fn string_vendor_event(&self) -> Option<u32> {
        None
    }

    /// Amps (InDCA)
    ///
    /// String Input Current
    fn string_amps(&self) -> i16;

    /// Amp-hours (InDCAhr)
    ///
    /// String Input Amp-Hours
    fn string_amp_hours(&self) -> Option<u32> {
        None
    }

    /// Voltage (InDCV)
    ///
    /// String Input Voltage
    fn string_voltage(&self) -> Option<u16> {
        None
    }

    /// Watts (InDCW)
    ///
    /// String Input Power
    fn string_watts(&self) -> Option<i16> {
        None
    }

    /// Watt-hours (InDCWh)
    ///
    /// String Input Energy
    fn string_watt_hours(&self) -> Option<u32> {
        None
    }

    /// PR (InDCPR)
    ///
    /// String Performance Ratio
    fn string_pr(&self) -> Option<u16> {
        None
    }

    /// N (InN)
    ///
    /// Number of modules in this input string
    fn string_n(&self) -> Option<u16> {
        None
    }
}

pub trait WriteAdapter {}
