// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use crate::{ModbusException, ModelSpec};
use core::cmp::min;

static POINTS: [PointDetails<()>; 61] = [
    PointDetails {
        point: |()| Point::ModelId,
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |()| Point::ModelLength,
        size: 1,
        start_address: 1,
    },
    PointDetails {
        point: |()| Point::RequestSequence,
        size: 1,
        start_address: 2,
    },
    PointDetails {
        point: |()| Point::Status,
        size: 1,
        start_address: 3,
    },
    PointDetails {
        point: |()| Point::X,
        size: 1,
        start_address: 4,
    },
    PointDetails {
        point: |()| Point::Value1,
        size: 1,
        start_address: 5,
    },
    PointDetails {
        point: |()| Point::Val2,
        size: 1,
        start_address: 6,
    },
    PointDetails {
        point: |()| Point::Val3,
        size: 1,
        start_address: 7,
    },
    PointDetails {
        point: |()| Point::Val4,
        size: 1,
        start_address: 8,
    },
    PointDetails {
        point: |()| Point::Val5,
        size: 1,
        start_address: 9,
    },
    PointDetails {
        point: |()| Point::Val6,
        size: 1,
        start_address: 10,
    },
    PointDetails {
        point: |()| Point::Val7,
        size: 1,
        start_address: 11,
    },
    PointDetails {
        point: |()| Point::Val8,
        size: 1,
        start_address: 12,
    },
    PointDetails {
        point: |()| Point::Val9,
        size: 1,
        start_address: 13,
    },
    PointDetails {
        point: |()| Point::Val10,
        size: 1,
        start_address: 14,
    },
    PointDetails {
        point: |()| Point::Val11,
        size: 1,
        start_address: 15,
    },
    PointDetails {
        point: |()| Point::Val12,
        size: 1,
        start_address: 16,
    },
    PointDetails {
        point: |()| Point::Val13,
        size: 1,
        start_address: 17,
    },
    PointDetails {
        point: |()| Point::Val14,
        size: 1,
        start_address: 18,
    },
    PointDetails {
        point: |()| Point::Val15,
        size: 1,
        start_address: 19,
    },
    PointDetails {
        point: |()| Point::Val16,
        size: 1,
        start_address: 20,
    },
    PointDetails {
        point: |()| Point::Val17,
        size: 1,
        start_address: 21,
    },
    PointDetails {
        point: |()| Point::Val18,
        size: 1,
        start_address: 22,
    },
    PointDetails {
        point: |()| Point::Val19,
        size: 1,
        start_address: 23,
    },
    PointDetails {
        point: |()| Point::Val20,
        size: 1,
        start_address: 24,
    },
    PointDetails {
        point: |()| Point::Val21,
        size: 1,
        start_address: 25,
    },
    PointDetails {
        point: |()| Point::Val22,
        size: 1,
        start_address: 26,
    },
    PointDetails {
        point: |()| Point::Val23,
        size: 1,
        start_address: 27,
    },
    PointDetails {
        point: |()| Point::Val24,
        size: 1,
        start_address: 28,
    },
    PointDetails {
        point: |()| Point::Val25,
        size: 1,
        start_address: 29,
    },
    PointDetails {
        point: |()| Point::Val26,
        size: 1,
        start_address: 30,
    },
    PointDetails {
        point: |()| Point::Val27,
        size: 1,
        start_address: 31,
    },
    PointDetails {
        point: |()| Point::Val28,
        size: 1,
        start_address: 32,
    },
    PointDetails {
        point: |()| Point::Val29,
        size: 1,
        start_address: 33,
    },
    PointDetails {
        point: |()| Point::Val30,
        size: 1,
        start_address: 34,
    },
    PointDetails {
        point: |()| Point::Val31,
        size: 1,
        start_address: 35,
    },
    PointDetails {
        point: |()| Point::Val32,
        size: 1,
        start_address: 36,
    },
    PointDetails {
        point: |()| Point::Val33,
        size: 1,
        start_address: 37,
    },
    PointDetails {
        point: |()| Point::Val34,
        size: 1,
        start_address: 38,
    },
    PointDetails {
        point: |()| Point::Val35,
        size: 1,
        start_address: 39,
    },
    PointDetails {
        point: |()| Point::Val36,
        size: 1,
        start_address: 40,
    },
    PointDetails {
        point: |()| Point::Val37,
        size: 1,
        start_address: 41,
    },
    PointDetails {
        point: |()| Point::Val38,
        size: 1,
        start_address: 42,
    },
    PointDetails {
        point: |()| Point::Val39,
        size: 1,
        start_address: 43,
    },
    PointDetails {
        point: |()| Point::Val40,
        size: 1,
        start_address: 44,
    },
    PointDetails {
        point: |()| Point::Val41,
        size: 1,
        start_address: 45,
    },
    PointDetails {
        point: |()| Point::Val42,
        size: 1,
        start_address: 46,
    },
    PointDetails {
        point: |()| Point::Val43,
        size: 1,
        start_address: 47,
    },
    PointDetails {
        point: |()| Point::Val44,
        size: 1,
        start_address: 48,
    },
    PointDetails {
        point: |()| Point::Val45,
        size: 1,
        start_address: 49,
    },
    PointDetails {
        point: |()| Point::Val46,
        size: 1,
        start_address: 50,
    },
    PointDetails {
        point: |()| Point::Val47,
        size: 1,
        start_address: 51,
    },
    PointDetails {
        point: |()| Point::Val48,
        size: 1,
        start_address: 52,
    },
    PointDetails {
        point: |()| Point::Val49,
        size: 1,
        start_address: 53,
    },
    PointDetails {
        point: |()| Point::Val50,
        size: 1,
        start_address: 54,
    },
    PointDetails {
        point: |()| Point::Timestamp,
        size: 2,
        start_address: 55,
    },
    PointDetails {
        point: |()| Point::Milliseconds,
        size: 1,
        start_address: 57,
    },
    PointDetails {
        point: |()| Point::Sequence,
        size: 1,
        start_address: 58,
    },
    PointDetails {
        point: |()| Point::Alarm,
        size: 1,
        start_address: 59,
    },
    PointDetails {
        point: |()| Point::Algorithm,
        size: 1,
        start_address: 60,
    },
    PointDetails {
        point: |()| Point::N,
        size: 1,
        start_address: 61,
    },
];

static REPEATING_POINTS: [PointDetails<()>; 1] = [PointDetails {
    point: |()| Point::RepeatingDs,
    size: 1,
    start_address: 0,
}];

#[derive(Debug)]
pub enum Point {
    ModelId,
    ModelLength,
    RequestSequence,
    Status,
    X,
    Value1,
    Val2,
    Val3,
    Val4,
    Val5,
    Val6,
    Val7,
    Val8,
    Val9,
    Val10,
    Val11,
    Val12,
    Val13,
    Val14,
    Val15,
    Val16,
    Val17,
    Val18,
    Val19,
    Val20,
    Val21,
    Val22,
    Val23,
    Val24,
    Val25,
    Val26,
    Val27,
    Val28,
    Val29,
    Val30,
    Val31,
    Val32,
    Val33,
    Val34,
    Val35,
    Val36,
    Val37,
    Val38,
    Val39,
    Val40,
    Val41,
    Val42,
    Val43,
    Val44,
    Val45,
    Val46,
    Val47,
    Val48,
    Val49,
    Val50,
    Timestamp,
    Milliseconds,
    Sequence,
    Alarm,
    Algorithm,
    N,
    RepeatingDs,
}

struct PointDetails<GroupIndexArgs> {
    point: fn(GroupIndexArgs) -> Point,
    start_address: u16,
    size: u16,
}

/// Marker for SunSpec model 4. Add it to a [`Sunspec`](crate::Sunspec) model list.
pub struct Model4;

impl<'ad> ModelSpec<'ad> for Model4 {
    const MODEL_ID: u16 = 4;
    type ReadAdapter = dyn ReadAdapter + 'ad;
    type WriteAdapter = dyn WriteAdapter + 'ad;

    fn model_length(&self) -> u16 {
        63
    }

    fn traverse_points_read<'a>(
        &self,
        adapter: Option<&Self::ReadAdapter>,
        buffer: &mut WritableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .chain(
                REPEATING_POINTS
                    .iter()
                    .map(move |p| (62 + p.start_address, p.size, (p.point)(()))),
            )
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            write_point_to_buffer(
                self,
                adapter,
                &point,
                &mut buffer.slice(cursor, word_count),
                point_offset,
            );
            cursor += word_count;
        }

        Ok(())
    }

    fn traverse_points_write<'a>(
        &self,
        adapter: &mut Self::WriteAdapter,
        buffer: &ReadableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .chain(
                REPEATING_POINTS
                    .iter()
                    .map(move |p| (62 + p.start_address, p.size, (p.point)(()))),
            )
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            if point_offset > 0 {
                return Err(ModbusException::IllegalDataAddress);
            }
            read_point_from_buffer(self, adapter, &point, &buffer.slice(cursor, word_count))?;
            cursor += word_count;
        }

        Ok(())
    }
}

pub(crate) fn write_point_to_buffer<'a>(
    model: &Model4,
    adapter: Option<&dyn ReadAdapter>,
    point: &Point,
    buffer: &mut WritableRegisterBuffer<'a>,
    offset: u16,
) {
    match point {
        Point::ModelId => {
            buffer.write_u16(4);
        }
        Point::ModelLength => {
            buffer.write_u16(model.model_length() - 2);
        }
        Point::RequestSequence => {
            if let Some(value) = adapter.map(|adapter| adapter.request_sequence()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Status => {
            if let Some(value) = adapter.map(|adapter| adapter.status()) {
                buffer.write_u16(value as u16);
            } else {
                buffer.write_u16(crate::not_implemented::ENUM16);
            }
        }
        Point::X => {
            if let Some(value) = adapter.map(|adapter| adapter.x()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Value1 => {
            if let Some(value) = adapter.map(|adapter| adapter.value1()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val2 => {
            if let Some(value) = adapter.map(|adapter| adapter.val2()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val3 => {
            if let Some(value) = adapter.map(|adapter| adapter.val3()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val4 => {
            if let Some(value) = adapter.map(|adapter| adapter.val4()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val5 => {
            if let Some(value) = adapter.map(|adapter| adapter.val5()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val6 => {
            if let Some(value) = adapter.map(|adapter| adapter.val6()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val7 => {
            if let Some(value) = adapter.map(|adapter| adapter.val7()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val8 => {
            if let Some(value) = adapter.map(|adapter| adapter.val8()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val9 => {
            if let Some(value) = adapter.map(|adapter| adapter.val9()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val10 => {
            if let Some(value) = adapter.map(|adapter| adapter.val10()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val11 => {
            if let Some(value) = adapter.map(|adapter| adapter.val11()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val12 => {
            if let Some(value) = adapter.map(|adapter| adapter.val12()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val13 => {
            if let Some(value) = adapter.map(|adapter| adapter.val13()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val14 => {
            if let Some(value) = adapter.map(|adapter| adapter.val14()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val15 => {
            if let Some(value) = adapter.map(|adapter| adapter.val15()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val16 => {
            if let Some(value) = adapter.map(|adapter| adapter.val16()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val17 => {
            if let Some(value) = adapter.map(|adapter| adapter.val17()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val18 => {
            if let Some(value) = adapter.map(|adapter| adapter.val18()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val19 => {
            if let Some(value) = adapter.map(|adapter| adapter.val19()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val20 => {
            if let Some(value) = adapter.map(|adapter| adapter.val20()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val21 => {
            if let Some(value) = adapter.map(|adapter| adapter.val21()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val22 => {
            if let Some(value) = adapter.map(|adapter| adapter.val22()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val23 => {
            if let Some(value) = adapter.map(|adapter| adapter.val23()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val24 => {
            if let Some(value) = adapter.map(|adapter| adapter.val24()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val25 => {
            if let Some(value) = adapter.map(|adapter| adapter.val25()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val26 => {
            if let Some(value) = adapter.map(|adapter| adapter.val26()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val27 => {
            if let Some(value) = adapter.map(|adapter| adapter.val27()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val28 => {
            if let Some(value) = adapter.map(|adapter| adapter.val28()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val29 => {
            if let Some(value) = adapter.map(|adapter| adapter.val29()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val30 => {
            if let Some(value) = adapter.map(|adapter| adapter.val30()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val31 => {
            if let Some(value) = adapter.map(|adapter| adapter.val31()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val32 => {
            if let Some(value) = adapter.map(|adapter| adapter.val32()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val33 => {
            if let Some(value) = adapter.map(|adapter| adapter.val33()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val34 => {
            if let Some(value) = adapter.map(|adapter| adapter.val34()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val35 => {
            if let Some(value) = adapter.map(|adapter| adapter.val35()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val36 => {
            if let Some(value) = adapter.map(|adapter| adapter.val36()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val37 => {
            if let Some(value) = adapter.map(|adapter| adapter.val37()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val38 => {
            if let Some(value) = adapter.map(|adapter| adapter.val38()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val39 => {
            if let Some(value) = adapter.map(|adapter| adapter.val39()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val40 => {
            if let Some(value) = adapter.map(|adapter| adapter.val40()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val41 => {
            if let Some(value) = adapter.map(|adapter| adapter.val41()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val42 => {
            if let Some(value) = adapter.map(|adapter| adapter.val42()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val43 => {
            if let Some(value) = adapter.map(|adapter| adapter.val43()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val44 => {
            if let Some(value) = adapter.map(|adapter| adapter.val44()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val45 => {
            if let Some(value) = adapter.map(|adapter| adapter.val45()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val46 => {
            if let Some(value) = adapter.map(|adapter| adapter.val46()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val47 => {
            if let Some(value) = adapter.map(|adapter| adapter.val47()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val48 => {
            if let Some(value) = adapter.map(|adapter| adapter.val48()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val49 => {
            if let Some(value) = adapter.map(|adapter| adapter.val49()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Val50 => {
            if let Some(value) = adapter.map(|adapter| adapter.val50()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Timestamp => {
            if let Some(value) = adapter.map(|adapter| adapter.timestamp()) {
                buffer.write_u32(value, offset);
            } else {
                buffer.write_u32(crate::not_implemented::UINT32, offset);
            }
        }
        Point::Milliseconds => {
            if let Some(value) = adapter.map(|adapter| adapter.milliseconds()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Sequence => {
            if let Some(value) = adapter.map(|adapter| adapter.sequence()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::Alarm => {
            if let Some(value) = adapter.map(|adapter| adapter.alarm()) {
                buffer.write_u16(value as u16);
            } else {
                buffer.write_u16(crate::not_implemented::ENUM16);
            }
        }
        Point::Algorithm => {
            if let Some(value) = adapter.map(|adapter| adapter.algorithm()) {
                buffer.write_u16(value as u16);
            } else {
                buffer.write_u16(crate::not_implemented::ENUM16);
            }
        }
        Point::N => {
            if let Some(value) = adapter.map(|adapter| adapter.n()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
        Point::RepeatingDs => {
            if let Some(value) = adapter.map(|adapter| adapter.repeating_ds()) {
                buffer.write_u16(value);
            } else {
                buffer.write_u16(crate::not_implemented::UINT16);
            }
        }
    }
}

pub(crate) fn read_point_from_buffer<'a>(
    model: &Model4,
    adapter: &mut dyn WriteAdapter,
    point: &Point,
    buffer: &ReadableRegisterBuffer<'a>,
) -> Result<(), ModbusException> {
    Err(ModbusException::IllegalDataAddress)
}

pub trait ReadAdapter {
    /// Request Sequence (RqSeq)
    ///
    /// Sequence number from the request
    fn request_sequence(&self) -> u16;

    /// Status (Sts)
    ///
    /// Status of last read operation
    fn status(&self) -> Sts;

    /// X (X)
    ///
    /// Number of values from the request
    ///
    /// A max of 50 values are allocated
    fn x(&self) -> u16;

    /// Value1 (Val1)
    ///
    /// Copy of value from register Off1.
    ///
    /// Unused values shall return 0xFFFF (unimplemented)
    fn value1(&self) -> u16;

    /// Val2
    fn val2(&self) -> u16;

    /// Val3
    fn val3(&self) -> u16;

    /// Val4
    fn val4(&self) -> u16;

    /// Val5
    fn val5(&self) -> u16;

    /// Val6
    fn val6(&self) -> u16;

    /// Val7
    fn val7(&self) -> u16;

    /// Val8
    fn val8(&self) -> u16;

    /// Val9
    fn val9(&self) -> u16;

    /// Val10
    fn val10(&self) -> u16;

    /// Val11
    fn val11(&self) -> u16;

    /// Val12
    fn val12(&self) -> u16;

    /// Val13
    fn val13(&self) -> u16;

    /// Val14
    fn val14(&self) -> u16;

    /// Val15
    fn val15(&self) -> u16;

    /// Val16
    fn val16(&self) -> u16;

    /// Val17
    fn val17(&self) -> u16;

    /// Val18
    fn val18(&self) -> u16;

    /// Val19
    fn val19(&self) -> u16;

    /// Val20
    fn val20(&self) -> u16;

    /// Val21
    fn val21(&self) -> u16;

    /// Val22
    fn val22(&self) -> u16;

    /// Val23
    fn val23(&self) -> u16;

    /// Val24
    fn val24(&self) -> u16;

    /// Val25
    fn val25(&self) -> u16;

    /// Val26
    fn val26(&self) -> u16;

    /// Val27
    fn val27(&self) -> u16;

    /// Val28
    fn val28(&self) -> u16;

    /// Val29
    fn val29(&self) -> u16;

    /// Val30
    fn val30(&self) -> u16;

    /// Val31
    fn val31(&self) -> u16;

    /// Val32
    fn val32(&self) -> u16;

    /// Val33
    fn val33(&self) -> u16;

    /// Val34
    fn val34(&self) -> u16;

    /// Val35
    fn val35(&self) -> u16;

    /// Val36
    fn val36(&self) -> u16;

    /// Val37
    fn val37(&self) -> u16;

    /// Val38
    fn val38(&self) -> u16;

    /// Val39
    fn val39(&self) -> u16;

    /// Val40
    fn val40(&self) -> u16;

    /// Val41
    fn val41(&self) -> u16;

    /// Val42
    fn val42(&self) -> u16;

    /// Val43
    fn val43(&self) -> u16;

    /// Val44
    fn val44(&self) -> u16;

    /// Val45
    fn val45(&self) -> u16;

    /// Val46
    fn val46(&self) -> u16;

    /// Val47
    fn val47(&self) -> u16;

    /// Val48
    fn val48(&self) -> u16;

    /// Val49
    fn val49(&self) -> u16;

    /// Val50
    fn val50(&self) -> u16;

    /// Timestamp (Ts)
    ///
    /// Timestamp value is the number of seconds since January 1, 2000
    fn timestamp(&self) -> u32;

    /// Milliseconds (Ms)
    ///
    /// Millisecond counter 0-999
    fn milliseconds(&self) -> u16;

    /// Sequence (Seq)
    ///
    /// Sequence number of response
    ///
    /// Shall be advanced for each response
    fn sequence(&self) -> u16;

    /// Alarm (Alm)
    ///
    /// Bitmask alarm code
    fn alarm(&self) -> Alm;

    /// Algorithm (Alg)
    ///
    /// Algorithm used to compute the digital signature
    ///
    /// For future proof
    fn algorithm(&self) -> Alg;

    /// N (N)
    ///
    /// Number of registers comprising the digital signature.
    ///
    /// The value of N must be at least 4 (64 bits)
    fn n(&self) -> u16;

    /// DS (DS)
    ///
    /// Digital Signature
    fn repeating_ds(&self) -> u16;
}

pub trait WriteAdapter {}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model4Alg {
    /// For test purposes only
    None = 0,
    AesGmac64 = 1,
    Ecc256 = 2,
}

impl Model4Alg {
    pub fn from_repr(repr: u16) -> Option<Model4Alg> {
        match repr {
            0 => Some(Model4Alg::None),
            1 => Some(Model4Alg::AesGmac64),
            2 => Some(Model4Alg::Ecc256),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model4Alg`] - only `Model4Alg` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `Alg` distinct from another model's point of the same name.
pub type Alg = Model4Alg;

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model4Alm {
    None = 0,
    /// Tampered
    Alm = 1,
}

impl Model4Alm {
    pub fn from_repr(repr: u16) -> Option<Model4Alm> {
        match repr {
            0 => Some(Model4Alm::None),
            1 => Some(Model4Alm::Alm),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model4Alm`] - only `Model4Alm` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `Alm` distinct from another model's point of the same name.
pub type Alm = Model4Alm;

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model4Sts {
    Success = 0,
    Ds = 1,
    /// One or more registers were not writable by this role
    Acl = 2,
    /// Offset out of range or missing from multi-register value
    Off = 3,
}

impl Model4Sts {
    pub fn from_repr(repr: u16) -> Option<Model4Sts> {
        match repr {
            0 => Some(Model4Sts::Success),
            1 => Some(Model4Sts::Ds),
            2 => Some(Model4Sts::Acl),
            3 => Some(Model4Sts::Off),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model4Sts`] - only `Model4Sts` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `Sts` distinct from another model's point of the same name.
pub type Sts = Model4Sts;
