use codegen::Scope;
use glob::glob;
use rustfmt_wrapper::config::{Config, Edition};
use std::process::Command;
use std::{ffi::OsStr, fs, path::Path};

use crate::code_generation::{
    generate_adapters_mod, generate_model, generate_models_mod, model_c_expressible,
    model_is_repeating,
};
use crate::model_resolution::{ResolvedModel, resolve_model};
use crate::naming::{NameTable, Named};
use crate::sunspec_schema::SunspecModel;

mod code_generation;
mod model_resolution;
mod naming;
mod sunspec_schema;

/// Renders a `//`-commented block to include at the top of generated Rust sources.
/// Includes a clear instructions on how to regenerate the file, and a reference to the specific SunSpec model tag
/// that was the source for generation.
/// `@generated` is the conventional marker various tools (GitHub Linguist, diff/review UIs) look for to treat a file
///  as generated rather than hand-written.
fn generated_file_comment(submodule_tag: &str) -> String {
    [
        "@generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in"
            .to_string(),
        format!("https://github.com/sunspec/models at tag {submodule_tag}."),
        "Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.".to_string(),
    ]
    .iter()
    .map(|line| format!("// {line}\n"))
    .collect()
}

fn get_submodule_tag(model_dir: &str) -> String {
    // Cleared because a git hook (this is invoked from lefthook's pre-commit) runs with
    // `GIT_INDEX_FILE`/`GIT_DIR` pointing at the main repository, currently mid-commit.
    // Left in place, that leaks into this `git describe` for the submodule: it still resolves
    // the right tag (repo discovery via `current_dir` isn't affected), but the `--dirty` check
    // diffs the submodule's working tree against the main repo's unrelated index instead of
    // its own, so it comes back dirty even when the submodule genuinely isn't.
    let git_command = || {
        let mut cmd = Command::new("git");
        cmd.current_dir(model_dir)
            .env_remove("GIT_DIR")
            .env_remove("GIT_WORK_TREE")
            .env_remove("GIT_INDEX_FILE")
            .env_remove("GIT_COMMON_DIR")
            .env_remove("GIT_OBJECT_DIRECTORY")
            .env_remove("GIT_ALTERNATE_OBJECT_DIRECTORIES")
            .env_remove("GIT_PREFIX");
        cmd
    };

    git_command()
        .args(["fetch", "--tags"])
        .output()
        .expect("Failed to fetch git submodule tags");

    let output = git_command()
        .args(["describe", "--tags", "--always", "--dirty"])
        .output()
        .expect("Failed to execute `git describe` to get current submodule tag");

    String::from_utf8(output.stdout)
        .expect("Invalid UTF-8 sequence for git submodule tag")
        .lines()
        .next()
        .unwrap_or_default()
        .to_string()
}

fn model_name_from_path(path: &Path) -> &str {
    path.file_prefix()
        .and_then(OsStr::to_str)
        .expect("Failed to convert Sunspec model JSON file name to string")
}

fn collect_models(model_glob: &str) -> Vec<ResolvedModel> {
    let mut vec: Vec<ResolvedModel> = glob(model_glob)
        .expect("Failed to find Sunspec model JSON files by glob pattern")
        .flat_map(|entry| match entry {
            Ok(path) => {
                let json = fs::read_to_string(&path).expect("Failed to read model JSON to string");
                let model: SunspecModel =
                    serde_json::from_str(&json).expect("Failed to parse Sunspec model as JSON");
                let model_name = model_name_from_path(path.as_path());
                Some(resolve_model(&model, model_name.to_string()))
            }
            Err(e) => {
                println!("{:?}", e);
                None
            }
        })
        .collect();

    // Model names are unique by construction (derived from each JSON file's own model number),
    // but are still run through a NameTable for the same reason as points, groups and enums:
    // a genuine collision then fails the build loudly instead of silently generating two
    // colliding items.
    let mut model_names = NameTable::default();
    for model in &vec {
        model_names.register_unique(model.name.clone());
    }
    model_names.deduplicate();

    vec.sort_unstable_by_key(|model| model.model_number);

    vec
}

fn format_and_write(path: &Path, scope: &Scope, submodule_tag: &str) {
    let text_raw = scope.to_string();

    let rustfmt_config: Config = Config {
        edition: Some(Edition::Edition2024),
        ..Default::default()
    };
    let formatted =
        rustfmt_wrapper::rustfmt_config(rustfmt_config, &text_raw).unwrap_or_else(|error| {
            println!(
                "cargo:warning=Error formatting file {}: [{}]. File left unformatted.",
                path.to_str().unwrap_or_default(),
                error
            );
            text_raw
        });

    // Added after formatting, not before: rustfmt is free to reflow this crate's own generated
    // code however it likes, but the notice itself should reach every file byte-for-byte as
    // written here.
    let text = format!("{}\n{formatted}", generated_file_comment(submodule_tag));
    fs::write(path, text).expect("Failed to write generated source to file");
}

pub fn generate() {
    let project_root = env!("CARGO_MANIFEST_DIR");
    let model_dir = format!("{project_root}/models");
    let model_glob = format!("{model_dir}/json/model_*.json");
    let src_path = format!("{project_root}/../sunspec-modbus-lib-rs/src/sunspec");
    let generated_src_dir = Path::new(&src_path);
    let submodule_tag = get_submodule_tag(&model_dir);

    fs::create_dir_all(generated_src_dir.join("models"))
        .expect("Failed to create generated source directories");

    let models = collect_models(&model_glob);

    for model in &models {
        format_and_write(
            &generated_src_dir
                .join("models")
                .join(format!("{}.rs", model.name_snake_case())),
            &generate_model(model),
            &submodule_tag,
        );
    }

    format_and_write(
        &generated_src_dir.join("models.rs"),
        &generate_models_mod(&models),
        &submodule_tag,
    );

    format_and_write(
        &generated_src_dir.join("adapters.rs"),
        &generate_adapters_mod(&models),
        &submodule_tag,
    );
}

/// Regenerates `sunspec-modbus-lib-static`'s typed `SunspecAdapter` constructors
/// (`src/generated.rs`).
pub fn generate_static_lib() {
    let project_root = env!("CARGO_MANIFEST_DIR");
    let model_dir = format!("{project_root}/models");
    let model_glob = format!("{model_dir}/json/model_*.json");
    let submodule_tag = get_submodule_tag(&model_dir);

    let output_path = Path::new(project_root).join("../sunspec-modbus-lib-static/src/generated.rs");

    let models = collect_models(&model_glob);
    format_and_write(
        &output_path,
        &generate_static_lib_adapter_ctors(&models),
        &submodule_tag,
    );
}

/// Typed `SunspecAdapter` constructors, one set per C-expressible model.
///
/// `sunspec_model_<id>_callback(*mut Model<id>CallbackAdapter)` /
/// `sunspec_model_<id>_stateful(*mut Model<id>StatefulAdapter)`
/// build a `SunspecAdapter` with the matching `model_spec`, `kind` and adapter pointer, so a C
/// caller cannot pair the wrong adapter type with a model (the C compiler rejects a mismatched
/// pointer) or leave the `model_spec`/`kind`/`adapter` triple inconsistent. `_stateful` is
/// generated only for non-repeating models, matching the dispatch code (repeating models have
/// no C-usable stateful adapter).
///
/// These are real `#[unsafe(no_mangle)] pub extern "C" fn`s, generated directly into
/// `sunspec-modbus-lib-static` rather than spliced into the header as C text: cbindgen exports
/// them itself, and naming `Model<id>{Stateful,Callback}Adapter` in their signatures is what
/// makes cbindgen carry those structs' field layout — no force-listing needed.
fn generate_static_lib_adapter_ctors(models: &[ResolvedModel]) -> Scope {
    let mut scope = Scope::new();
    scope.raw("#![allow(unused_imports)]");
    scope.raw("use core::ffi::c_void;");
    scope.raw(
        "use crate::{SunspecAdapter, SUNSPEC_ADAPTER_CALLBACK, SUNSPEC_ADAPTER_NONE, SUNSPEC_ADAPTER_STATEFUL};",
    );

    for model in models.iter().filter(|model| model_c_expressible(model)) {
        let n = model.model_number;
        let sc = &model.name_snake_case();
        let pc = &model.name_pascal_case();
        let module = format!("sunspec_modbus_lib_rs::sunspec::models::{sc}");

        scope.raw(format!(
            "/// Build a [`SunspecAdapter`] for model {n} backed by a callback adapter.\n\
             #[unsafe(no_mangle)]\n\
             pub extern \"C\" fn sunspec_model_{n}_callback(\n\
             \x20   adapter: *mut {module}::{pc}CallbackAdapter,\n\
             ) -> SunspecAdapter {{\n\
             \x20   SunspecAdapter {{\n\
             \x20       model_spec: &{module}::SUNSPEC_MODEL_{n},\n\
             \x20       kind: SUNSPEC_ADAPTER_CALLBACK,\n\
             \x20       adapter: adapter as *mut c_void,\n\
             \x20   }}\n\
             }}\n"
        ));

        if !model_is_repeating(model) {
            scope.raw(format!(
                "/// Build a [`SunspecAdapter`] for model {n} backed by a stateful adapter.\n\
                 #[unsafe(no_mangle)]\n\
                 pub extern \"C\" fn sunspec_model_{n}_stateful(\n\
                 \x20   adapter: *mut {module}::{pc}StatefulAdapter,\n\
                 ) -> SunspecAdapter {{\n\
                 \x20   SunspecAdapter {{\n\
                 \x20       model_spec: &{module}::SUNSPEC_MODEL_{n},\n\
                 \x20       kind: SUNSPEC_ADAPTER_STATEFUL,\n\
                 \x20       adapter: adapter as *mut c_void,\n\
                 \x20   }}\n\
                 }}\n"
            ));
        }
    }

    scope
}
