// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20-dirty
.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use crate::cursor::Cursor;
use crate::model::StaticModelSpec;
use crate::sunspec::models::*;
use crate::{ModbusException, ModelSpec};
use core::ffi::c_void;

/// One model's read side: a statically known model paired with a shared borrow of
/// its per-model [`ReadAdapter`](crate::sunspec::models) trait, or an
/// [`Extern`](ReadBinding::Extern) block dispatched through a C [`StaticModelSpec`] vtable.
#[non_exhaustive]
pub enum ReadBinding<'a> {
    Model1(&'a model_1::Model1, &'a dyn model_1::ReadAdapter),
    Model2(&'a model_2::Model2, &'a dyn model_2::ReadAdapter),
    Model3(&'a model_3::Model3, &'a dyn model_3::ReadAdapter),
    Model4(&'a model_4::Model4, &'a dyn model_4::ReadAdapter),
    Model5(&'a model_5::Model5, &'a dyn model_5::ReadAdapter),
    Model6(&'a model_6::Model6, &'a dyn model_6::ReadAdapter),
    Model7(&'a model_7::Model7, &'a dyn model_7::ReadAdapter),
    Model8(&'a model_8::Model8, &'a dyn model_8::ReadAdapter),
    Model9(&'a model_9::Model9, &'a dyn model_9::ReadAdapter),
    Model10(&'a model_10::Model10, &'a dyn model_10::ReadAdapter),
    Model11(&'a model_11::Model11, &'a dyn model_11::ReadAdapter),
    Model12(&'a model_12::Model12, &'a dyn model_12::ReadAdapter),
    Model13(&'a model_13::Model13, &'a dyn model_13::ReadAdapter),
    Model14(&'a model_14::Model14, &'a dyn model_14::ReadAdapter),
    Model15(&'a model_15::Model15, &'a dyn model_15::ReadAdapter),
    Model16(&'a model_16::Model16, &'a dyn model_16::ReadAdapter),
    Model17(&'a model_17::Model17, &'a dyn model_17::ReadAdapter),
    Model18(&'a model_18::Model18, &'a dyn model_18::ReadAdapter),
    Model19(&'a model_19::Model19, &'a dyn model_19::ReadAdapter),
    Model101(&'a model_101::Model101, &'a dyn model_101::ReadAdapter),
    Model102(&'a model_102::Model102, &'a dyn model_102::ReadAdapter),
    Model103(&'a model_103::Model103, &'a dyn model_103::ReadAdapter),
    Model111(&'a model_111::Model111, &'a dyn model_111::ReadAdapter),
    Model112(&'a model_112::Model112, &'a dyn model_112::ReadAdapter),
    Model113(&'a model_113::Model113, &'a dyn model_113::ReadAdapter),
    Model120(&'a model_120::Model120, &'a dyn model_120::ReadAdapter),
    Model121(&'a model_121::Model121, &'a dyn model_121::ReadAdapter),
    Model122(&'a model_122::Model122, &'a dyn model_122::ReadAdapter),
    Model123(&'a model_123::Model123, &'a dyn model_123::ReadAdapter),
    Model124(&'a model_124::Model124, &'a dyn model_124::ReadAdapter),
    Model125(&'a model_125::Model125, &'a dyn model_125::ReadAdapter),
    Model126(&'a model_126::Model126, &'a dyn model_126::ReadAdapter),
    Model127(&'a model_127::Model127, &'a dyn model_127::ReadAdapter),
    Model128(&'a model_128::Model128, &'a dyn model_128::ReadAdapter),
    Model129(&'a model_129::Model129, &'a dyn model_129::ReadAdapter),
    Model130(&'a model_130::Model130, &'a dyn model_130::ReadAdapter),
    Model131(&'a model_131::Model131, &'a dyn model_131::ReadAdapter),
    Model132(&'a model_132::Model132, &'a dyn model_132::ReadAdapter),
    Model133(&'a model_133::Model133, &'a dyn model_133::ReadAdapter),
    Model134(&'a model_134::Model134, &'a dyn model_134::ReadAdapter),
    Model135(&'a model_135::Model135, &'a dyn model_135::ReadAdapter),
    Model136(&'a model_136::Model136, &'a dyn model_136::ReadAdapter),
    Model137(&'a model_137::Model137, &'a dyn model_137::ReadAdapter),
    Model138(&'a model_138::Model138, &'a dyn model_138::ReadAdapter),
    Model139(&'a model_139::Model139, &'a dyn model_139::ReadAdapter),
    Model140(&'a model_140::Model140, &'a dyn model_140::ReadAdapter),
    Model141(&'a model_141::Model141, &'a dyn model_141::ReadAdapter),
    Model142(&'a model_142::Model142, &'a dyn model_142::ReadAdapter),
    Model143(&'a model_143::Model143, &'a dyn model_143::ReadAdapter),
    Model144(&'a model_144::Model144, &'a dyn model_144::ReadAdapter),
    Model145(&'a model_145::Model145, &'a dyn model_145::ReadAdapter),
    Model160(&'a model_160::Model160, &'a dyn model_160::ReadAdapter),
    Model201(&'a model_201::Model201, &'a dyn model_201::ReadAdapter),
    Model202(&'a model_202::Model202, &'a dyn model_202::ReadAdapter),
    Model203(&'a model_203::Model203, &'a dyn model_203::ReadAdapter),
    Model204(&'a model_204::Model204, &'a dyn model_204::ReadAdapter),
    Model211(&'a model_211::Model211, &'a dyn model_211::ReadAdapter),
    Model212(&'a model_212::Model212, &'a dyn model_212::ReadAdapter),
    Model213(&'a model_213::Model213, &'a dyn model_213::ReadAdapter),
    Model214(&'a model_214::Model214, &'a dyn model_214::ReadAdapter),
    Model220(&'a model_220::Model220, &'a dyn model_220::ReadAdapter),
    Model302(&'a model_302::Model302, &'a dyn model_302::ReadAdapter),
    Model303(&'a model_303::Model303, &'a dyn model_303::ReadAdapter),
    Model304(&'a model_304::Model304, &'a dyn model_304::ReadAdapter),
    Model305(&'a model_305::Model305, &'a dyn model_305::ReadAdapter),
    Model306(&'a model_306::Model306, &'a dyn model_306::ReadAdapter),
    Model307(&'a model_307::Model307, &'a dyn model_307::ReadAdapter),
    Model308(&'a model_308::Model308, &'a dyn model_308::ReadAdapter),
    Model401(&'a model_401::Model401, &'a dyn model_401::ReadAdapter),
    Model402(&'a model_402::Model402, &'a dyn model_402::ReadAdapter),
    Model403(&'a model_403::Model403, &'a dyn model_403::ReadAdapter),
    Model404(&'a model_404::Model404, &'a dyn model_404::ReadAdapter),
    Model501(&'a model_501::Model501, &'a dyn model_501::ReadAdapter),
    Model502(&'a model_502::Model502, &'a dyn model_502::ReadAdapter),
    Model601(&'a model_601::Model601, &'a dyn model_601::ReadAdapter),
    Model701(&'a model_701::Model701, &'a dyn model_701::ReadAdapter),
    Model702(&'a model_702::Model702, &'a dyn model_702::ReadAdapter),
    Model703(&'a model_703::Model703, &'a dyn model_703::ReadAdapter),
    Model704(&'a model_704::Model704, &'a dyn model_704::ReadAdapter),
    Model705(&'a model_705::Model705, &'a dyn model_705::ReadAdapter),
    Model706(&'a model_706::Model706, &'a dyn model_706::ReadAdapter),
    Model707(&'a model_707::Model707, &'a dyn model_707::ReadAdapter),
    Model708(&'a model_708::Model708, &'a dyn model_708::ReadAdapter),
    Model709(&'a model_709::Model709, &'a dyn model_709::ReadAdapter),
    Model710(&'a model_710::Model710, &'a dyn model_710::ReadAdapter),
    Model711(&'a model_711::Model711, &'a dyn model_711::ReadAdapter),
    Model712(&'a model_712::Model712, &'a dyn model_712::ReadAdapter),
    Model713(&'a model_713::Model713, &'a dyn model_713::ReadAdapter),
    Model714(&'a model_714::Model714, &'a dyn model_714::ReadAdapter),
    Model715(&'a model_715::Model715, &'a dyn model_715::ReadAdapter),
    Model801(&'a model_801::Model801, &'a dyn model_801::ReadAdapter),
    Model802(&'a model_802::Model802, &'a dyn model_802::ReadAdapter),
    Model803(&'a model_803::Model803, &'a dyn model_803::ReadAdapter),
    Model804(&'a model_804::Model804, &'a dyn model_804::ReadAdapter),
    Model805(&'a model_805::Model805, &'a dyn model_805::ReadAdapter),
    Model806(&'a model_806::Model806, &'a dyn model_806::ReadAdapter),
    Model807(&'a model_807::Model807, &'a dyn model_807::ReadAdapter),
    Model808(&'a model_808::Model808, &'a dyn model_808::ReadAdapter),
    Model809(&'a model_809::Model809, &'a dyn model_809::ReadAdapter),
    Model63001(
        &'a model_63001::Model63001,
        &'a dyn model_63001::ReadAdapter,
    ),
    Model63002(
        &'a model_63002::Model63002,
        &'a dyn model_63002::ReadAdapter,
    ),
    Model64001(
        &'a model_64001::Model64001,
        &'a dyn model_64001::ReadAdapter,
    ),
    Model64020(
        &'a model_64020::Model64020,
        &'a dyn model_64020::ReadAdapter,
    ),
    Model64101(
        &'a model_64101::Model64101,
        &'a dyn model_64101::ReadAdapter,
    ),
    Model64111(
        &'a model_64111::Model64111,
        &'a dyn model_64111::ReadAdapter,
    ),
    Model64112(
        &'a model_64112::Model64112,
        &'a dyn model_64112::ReadAdapter,
    ),
    Model64410(
        &'a model_64410::Model64410,
        &'a dyn model_64410::ReadAdapter,
    ),
    Model64411(
        &'a model_64411::Model64411,
        &'a dyn model_64411::ReadAdapter,
    ),
    Model64412(
        &'a model_64412::Model64412,
        &'a dyn model_64412::ReadAdapter,
    ),
    Model64413(
        &'a model_64413::Model64413,
        &'a dyn model_64413::ReadAdapter,
    ),
    Model64414(
        &'a model_64414::Model64414,
        &'a dyn model_64414::ReadAdapter,
    ),
    Model64415(
        &'a model_64415::Model64415,
        &'a dyn model_64415::ReadAdapter,
    ),
    /// A model dispatched through a C [`StaticModelSpec`] vtable rather than a statically
    /// known model type. Produced by the FFI `ModelList` in `sunspec-modbus-lib-static`.
    ///
    /// # Safety
    /// Building this variant asserts `descriptor` and `adapter` uphold
    /// [`StaticModelSpec::visit_read`]'s contract: for `kind` 1 or 2, `adapter` points to
    /// a live `Model<id>{Stateful,Callback}Adapter` valid for the traversal.
    Extern {
        descriptor: &'a StaticModelSpec,
        kind: u8,
        adapter: *const c_void,
        repeat_count_0: u16,
        repeat_count_1: u16,
    },
}

/// One model's write side: a statically known model, carrying a uniquely borrowed
/// reference to its per-model [`WriteAdapter`](crate::sunspec::models) trait when the
/// model has writable points, or an [`Extern`](WriteBinding::Extern) block dispatched
/// through a C [`StaticModelSpec`] vtable. A variant with no adapter rejects every
/// write in its block.
#[non_exhaustive]
pub enum WriteBinding<'a> {
    Model1(&'a model_1::Model1, &'a mut dyn model_1::WriteAdapter),
    Model2(&'a model_2::Model2),
    Model3(&'a model_3::Model3, &'a mut dyn model_3::WriteAdapter),
    Model4(&'a model_4::Model4),
    Model5(&'a model_5::Model5, &'a mut dyn model_5::WriteAdapter),
    Model6(&'a model_6::Model6, &'a mut dyn model_6::WriteAdapter),
    Model7(&'a model_7::Model7, &'a mut dyn model_7::WriteAdapter),
    Model8(&'a model_8::Model8),
    Model9(&'a model_9::Model9, &'a mut dyn model_9::WriteAdapter),
    Model10(&'a model_10::Model10, &'a mut dyn model_10::WriteAdapter),
    Model11(&'a model_11::Model11, &'a mut dyn model_11::WriteAdapter),
    Model12(&'a model_12::Model12, &'a mut dyn model_12::WriteAdapter),
    Model13(&'a model_13::Model13, &'a mut dyn model_13::WriteAdapter),
    Model14(&'a model_14::Model14, &'a mut dyn model_14::WriteAdapter),
    Model15(&'a model_15::Model15, &'a mut dyn model_15::WriteAdapter),
    Model16(&'a model_16::Model16, &'a mut dyn model_16::WriteAdapter),
    Model17(&'a model_17::Model17, &'a mut dyn model_17::WriteAdapter),
    Model18(&'a model_18::Model18, &'a mut dyn model_18::WriteAdapter),
    Model19(&'a model_19::Model19, &'a mut dyn model_19::WriteAdapter),
    Model101(&'a model_101::Model101),
    Model102(&'a model_102::Model102),
    Model103(&'a model_103::Model103),
    Model111(&'a model_111::Model111),
    Model112(&'a model_112::Model112),
    Model113(&'a model_113::Model113),
    Model120(&'a model_120::Model120),
    Model121(&'a model_121::Model121, &'a mut dyn model_121::WriteAdapter),
    Model122(&'a model_122::Model122),
    Model123(&'a model_123::Model123, &'a mut dyn model_123::WriteAdapter),
    Model124(&'a model_124::Model124, &'a mut dyn model_124::WriteAdapter),
    Model125(&'a model_125::Model125, &'a mut dyn model_125::WriteAdapter),
    Model126(&'a model_126::Model126, &'a mut dyn model_126::WriteAdapter),
    Model127(&'a model_127::Model127, &'a mut dyn model_127::WriteAdapter),
    Model128(&'a model_128::Model128, &'a mut dyn model_128::WriteAdapter),
    Model129(&'a model_129::Model129, &'a mut dyn model_129::WriteAdapter),
    Model130(&'a model_130::Model130, &'a mut dyn model_130::WriteAdapter),
    Model131(&'a model_131::Model131, &'a mut dyn model_131::WriteAdapter),
    Model132(&'a model_132::Model132, &'a mut dyn model_132::WriteAdapter),
    Model133(&'a model_133::Model133, &'a mut dyn model_133::WriteAdapter),
    Model134(&'a model_134::Model134, &'a mut dyn model_134::WriteAdapter),
    Model135(&'a model_135::Model135, &'a mut dyn model_135::WriteAdapter),
    Model136(&'a model_136::Model136, &'a mut dyn model_136::WriteAdapter),
    Model137(&'a model_137::Model137, &'a mut dyn model_137::WriteAdapter),
    Model138(&'a model_138::Model138, &'a mut dyn model_138::WriteAdapter),
    Model139(&'a model_139::Model139, &'a mut dyn model_139::WriteAdapter),
    Model140(&'a model_140::Model140, &'a mut dyn model_140::WriteAdapter),
    Model141(&'a model_141::Model141, &'a mut dyn model_141::WriteAdapter),
    Model142(&'a model_142::Model142, &'a mut dyn model_142::WriteAdapter),
    Model143(&'a model_143::Model143, &'a mut dyn model_143::WriteAdapter),
    Model144(&'a model_144::Model144, &'a mut dyn model_144::WriteAdapter),
    Model145(&'a model_145::Model145, &'a mut dyn model_145::WriteAdapter),
    Model160(&'a model_160::Model160),
    Model201(&'a model_201::Model201),
    Model202(&'a model_202::Model202),
    Model203(&'a model_203::Model203),
    Model204(&'a model_204::Model204),
    Model211(&'a model_211::Model211),
    Model212(&'a model_212::Model212),
    Model213(&'a model_213::Model213),
    Model214(&'a model_214::Model214),
    Model220(&'a model_220::Model220),
    Model302(&'a model_302::Model302),
    Model303(&'a model_303::Model303),
    Model304(&'a model_304::Model304),
    Model305(&'a model_305::Model305),
    Model306(&'a model_306::Model306),
    Model307(&'a model_307::Model307),
    Model308(&'a model_308::Model308),
    Model401(&'a model_401::Model401),
    Model402(&'a model_402::Model402),
    Model403(&'a model_403::Model403),
    Model404(&'a model_404::Model404),
    Model501(&'a model_501::Model501, &'a mut dyn model_501::WriteAdapter),
    Model502(&'a model_502::Model502, &'a mut dyn model_502::WriteAdapter),
    Model601(&'a model_601::Model601, &'a mut dyn model_601::WriteAdapter),
    Model701(&'a model_701::Model701),
    Model702(&'a model_702::Model702, &'a mut dyn model_702::WriteAdapter),
    Model703(&'a model_703::Model703, &'a mut dyn model_703::WriteAdapter),
    Model704(&'a model_704::Model704, &'a mut dyn model_704::WriteAdapter),
    Model705(&'a model_705::Model705, &'a mut dyn model_705::WriteAdapter),
    Model706(&'a model_706::Model706, &'a mut dyn model_706::WriteAdapter),
    Model707(&'a model_707::Model707, &'a mut dyn model_707::WriteAdapter),
    Model708(&'a model_708::Model708, &'a mut dyn model_708::WriteAdapter),
    Model709(&'a model_709::Model709, &'a mut dyn model_709::WriteAdapter),
    Model710(&'a model_710::Model710, &'a mut dyn model_710::WriteAdapter),
    Model711(&'a model_711::Model711, &'a mut dyn model_711::WriteAdapter),
    Model712(&'a model_712::Model712, &'a mut dyn model_712::WriteAdapter),
    Model713(&'a model_713::Model713),
    Model714(&'a model_714::Model714),
    Model715(&'a model_715::Model715, &'a mut dyn model_715::WriteAdapter),
    Model801(&'a model_801::Model801),
    Model802(&'a model_802::Model802, &'a mut dyn model_802::WriteAdapter),
    Model803(&'a model_803::Model803, &'a mut dyn model_803::WriteAdapter),
    Model804(&'a model_804::Model804, &'a mut dyn model_804::WriteAdapter),
    Model805(&'a model_805::Model805),
    Model806(&'a model_806::Model806),
    Model807(&'a model_807::Model807, &'a mut dyn model_807::WriteAdapter),
    Model808(&'a model_808::Model808),
    Model809(&'a model_809::Model809),
    Model63001(
        &'a model_63001::Model63001,
        &'a mut dyn model_63001::WriteAdapter,
    ),
    Model63002(
        &'a model_63002::Model63002,
        &'a mut dyn model_63002::WriteAdapter,
    ),
    Model64001(
        &'a model_64001::Model64001,
        &'a mut dyn model_64001::WriteAdapter,
    ),
    Model64020(&'a model_64020::Model64020),
    Model64101(&'a model_64101::Model64101),
    Model64111(&'a model_64111::Model64111),
    Model64112(&'a model_64112::Model64112),
    Model64410(
        &'a model_64410::Model64410,
        &'a mut dyn model_64410::WriteAdapter,
    ),
    Model64411(
        &'a model_64411::Model64411,
        &'a mut dyn model_64411::WriteAdapter,
    ),
    Model64412(
        &'a model_64412::Model64412,
        &'a mut dyn model_64412::WriteAdapter,
    ),
    Model64413(&'a model_64413::Model64413),
    Model64414(
        &'a model_64414::Model64414,
        &'a mut dyn model_64414::WriteAdapter,
    ),
    Model64415(
        &'a model_64415::Model64415,
        &'a mut dyn model_64415::WriteAdapter,
    ),
    /// A model dispatched through a C [`StaticModelSpec`] vtable rather than a statically
    /// known model type. Produced by the FFI `ModelList` in `sunspec-modbus-lib-static`.
    ///
    /// # Safety
    /// Building this variant asserts `descriptor` and `adapter` uphold
    /// [`StaticModelSpec::visit_write`]'s contract: for `kind` 1 or 2, `adapter` is
    /// uniquely borrowable and points to a live `Model<id>{Stateful,Callback}Adapter`
    /// valid for the traversal.
    Extern {
        descriptor: &'a StaticModelSpec,
        kind: u8,
        adapter: *mut c_void,
        repeat_count_0: u16,
        repeat_count_1: u16,
    },
}

/// Encode one model's block into `buffer` from its matched [`ReadBinding`] variant,
/// advancing `cursor` across the block whether or not it produces data.
pub fn read_model<'a>(
    adapter: ReadBinding<'a>,
    cursor: &mut Cursor<ModbusException>,
    buffer: &mut WritableRegisterBuffer<'_>,
) {
    match adapter {
        ReadBinding::Model1(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model2(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model3(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model4(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model5(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model6(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model7(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model8(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model9(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model10(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model11(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model12(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model13(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model14(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model15(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model16(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model17(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model18(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model19(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model101(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model102(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model103(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model111(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model112(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model113(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model120(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model121(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model122(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model123(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model124(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model125(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model126(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model127(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model128(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model129(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model130(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model131(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model132(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model133(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model134(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model135(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model136(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model137(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model138(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model139(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model140(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model141(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model142(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model143(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model144(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model145(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model160(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model201(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model202(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model203(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model204(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model211(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model212(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model213(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model214(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model220(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model302(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model303(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model304(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model305(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model306(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model307(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model308(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model401(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model402(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model403(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model404(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model501(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model502(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model601(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model701(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model702(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model703(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model704(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model705(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model706(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model707(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model708(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model709(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model710(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model711(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model712(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model713(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model714(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model715(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model801(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model802(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model803(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model804(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model805(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model806(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model807(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model808(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model809(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model63001(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model63002(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model64001(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model64020(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model64101(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model64111(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model64112(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model64410(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model64411(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model64412(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model64413(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model64414(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Model64415(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_read(&*adapter, &mut buffer.slice(from, len), offset)
            });
        }
        ReadBinding::Extern {
            descriptor,
            kind,
            adapter,
            repeat_count_0,
            repeat_count_1,
        } => {
            // SAFETY: `ReadBinding::Extern` upholds `StaticModelSpec::visit_read`'s contract by construction.
            unsafe {
                (descriptor.visit_read)(
                    kind,
                    adapter,
                    repeat_count_0,
                    repeat_count_1,
                    cursor,
                    buffer,
                );
            }
        }
    }
}

/// Decode one model's block from `buffer` into its matched [`WriteBinding`] variant,
/// advancing `cursor` across the block. A non-writable variant rejects the write with
/// [`ModbusException::IllegalDataAddress`].
pub fn write_model<'a>(
    adapter: WriteBinding<'a>,
    cursor: &mut Cursor<ModbusException>,
    buffer: &ReadableRegisterBuffer<'_>,
) {
    match adapter {
        WriteBinding::Model1(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model2(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model3(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model4(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model5(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model6(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model7(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model8(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model9(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model10(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model11(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model12(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model13(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model14(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model15(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model16(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model17(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model18(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model19(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model101(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model102(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model103(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model111(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model112(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model113(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model120(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model121(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model122(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model123(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model124(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model125(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model126(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model127(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model128(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model129(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model130(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model131(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model132(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model133(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model134(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model135(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model136(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model137(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model138(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model139(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model140(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model141(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model142(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model143(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model144(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model145(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model160(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model201(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model202(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model203(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model204(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model211(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model212(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model213(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model214(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model220(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model302(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model303(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model304(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model305(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model306(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model307(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model308(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model401(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model402(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model403(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model404(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model501(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model502(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model601(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model701(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model702(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model703(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model704(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model705(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model706(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model707(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model708(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model709(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model710(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model711(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model712(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model713(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model714(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model715(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model801(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model802(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model803(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model804(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model805(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model806(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model807(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model808(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model809(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model63001(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model63002(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model64001(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model64020(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model64101(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model64111(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model64112(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model64410(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model64411(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model64412(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model64413(model) => {
            cursor.visit_source_block(model.model_length(), |_, _, _| {
                Err(ModbusException::IllegalDataAddress)
            });
        }
        WriteBinding::Model64414(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Model64415(model, adapter) => {
            cursor.visit_source_block(model.model_length(), |offset, from, len| {
                model.traverse_points_write(adapter, &buffer.slice(from, len), offset)
            });
        }
        WriteBinding::Extern {
            descriptor,
            kind,
            adapter,
            repeat_count_0,
            repeat_count_1,
        } => {
            // SAFETY: `WriteBinding::Extern` upholds `StaticModelSpec::visit_write`'s contract by construction.
            unsafe {
                (descriptor.visit_write)(
                    kind,
                    adapter,
                    repeat_count_0,
                    repeat_count_1,
                    cursor,
                    buffer,
                );
            }
        }
    }
}
